/* AUTO-GENERATED by tools/build-pages.mjs — do not edit by hand. */
export const navLabels = {
  "fa": {
    "nav.dash-analytics": "آنالیتیکس",
    "nav.dash-ecommerce": "فروشگاهی",
    "nav.dash-crm": "مدیریت مشتریان",
    "nav.dash-saas": "سرویس ابری",
    "nav.dash-finance": "مالی",
    "nav.dash-projects": "مدیریت پروژه",
    "nav.dash-hr": "منابع انسانی",
    "nav.dash-support": "پشتیبانی",
    "nav.dash-ai": "هوش مصنوعی",
    "nav.dash-logistics": "لجستیک",
    "nav.widgets": "ابزارک‌ها",
    "nav.ai-dashboard": "داشبورد AI",
    "nav.ai-chat": "گفتگوی هوشمند",
    "nav.ai-writer": "نویسنده هوشمند",
    "nav.ai-summarizer": "خلاصه‌ساز",
    "nav.ai-repurposer": "بازتولید محتوا",
    "nav.ai-prompts": "کتابخانه پرامپت",
    "nav.ai-scheduler": "زمان‌بند AI",
    "nav.ai-images": "استودیو تصویر",
    "nav.ai-usage": "مصرف و هزینه",
    "nav.ai-models": "مدل‌ها",
    "nav.ai-keys": "کلیدهای API",
    "nav.ai-history": "تاریخچه AI",
    "nav.ec-products": "محصولات",
    "nav.ec-grid": "نمایش شبکه‌ای",
    "nav.ec-details": "جزئیات محصول",
    "nav.ec-create": "افزودن محصول",
    "nav.ec-categories": "دسته‌بندی‌ها",
    "nav.ec-brands": "برندها",
    "nav.ec-tags": "برچسب‌ها",
    "nav.ec-inventory": "موجودی انبار",
    "nav.ec-reviews": "دیدگاه‌ها",
    "nav.ec-coupons": "کدهای تخفیف",
    "nav.ec-orders": "سفارش‌ها",
    "nav.ec-order-details": "جزئیات سفارش",
    "nav.crm-pipeline": "قیف فروش",
    "nav.crm-contacts": "مخاطبین",
    "nav.crm-companies": "شرکت‌ها",
    "nav.crm-leads": "سرنخ‌ها",
    "nav.crm-deals": "معاملات",
    "nav.crm-activities": "فعالیت‌ها",
    "nav.crm-contact-details-html": "جزئیات مخاطب",
    "nav.crm-company-details-html": "جزئیات شرکت",
    "nav.crm-deal-details-html": "جزئیات معامله",
    "nav.crm-calls": "تماس‌ها",
    "nav.crm-meetings": "جلسات",
    "nav.crm-campaigns": "کمپین‌ها",
    "nav.fin-overview": "نمای کلی",
    "nav.fin-transactions": "تراکنش‌ها",
    "nav.fin-accounts": "حساب‌ها",
    "nav.fin-expenses": "هزینه‌ها",
    "nav.fin-income": "درآمدها",
    "nav.fin-payments": "پرداخت‌ها",
    "nav.fin-invoices": "فاکتورها",
    "nav.fin-invoice-details": "جزئیات فاکتور",
    "nav.fin-subscriptions": "اشتراک‌ها",
    "nav.fin-payouts": "تسویه‌ها",
    "nav.prj-list": "لیست پروژه‌ها",
    "nav.prj-details": "جزئیات پروژه",
    "nav.prj-tasks": "وظایف",
    "nav.prj-kanban": "کانبان",
    "nav.prj-timeline": "خط زمان",
    "nav.sup-tickets": "تیکت‌ها",
    "nav.sup-details": "جزئیات تیکت",
    "nav.sup-agents": "کارشناسان",
    "nav.sup-kb": "پایگاه دانش",
    "nav.hr-employees": "کارکنان",
    "nav.hr-profile": "پروفایل کارمند",
    "nav.hr-attendance": "حضور و غیاب",
    "nav.hr-leave": "مرخصی‌ها",
    "nav.hr-payroll": "حقوق و دستمزد",
    "nav.hr-departments": "دپارتمان‌ها",
    "nav.hr-recruitment": "استخدام",
    "nav.log-shipments": "محموله‌ها",
    "nav.log-tracking": "رهگیری زنده",
    "nav.log-drivers": "رانندگان",
    "nav.log-warehouses": "انبارها",
    "nav.chat": "گفتگو",
    "nav.email": "ایمیل",
    "nav.calendar": "تقویم",
    "nav.files": "مدیریت فایل",
    "nav.media": "کتابخانه رسانه",
    "nav.notifications": "اعلان‌ها",
    "nav.users-list": "لیست کاربران",
    "nav.users-grid": "نمایش شبکه‌ای",
    "nav.users-create": "افزودن کاربر",
    "nav.users-details": "پروفایل کاربر",
    "nav.users-roles": "نقش‌ها",
    "nav.users-permissions": "مجوزها",
    "nav.users-teams": "تیم‌ها",
    "nav.users-departments": "دپارتمان‌ها",
    "nav.users-invitations": "دعوت‌نامه‌ها",
    "nav.users-activity": "فعالیت کاربران",
    "nav.users-sessions": "نشست‌ها",
    "nav.cust-list": "لیست مشتریان",
    "nav.cust-details": "پروفایل مشتری",
    "nav.cust-orders": "سفارش‌های مشتری",
    "nav.cust-segments": "بخش‌بندی",
    "nav.rep-sales": "فروش",
    "nav.rep-revenue": "درآمد",
    "nav.rep-customers": "مشتریان",
    "nav.rep-products": "محصولات",
    "nav.rep-finance": "مالی",
    "nav.rep-performance": "عملکرد",
    "nav.rep-traffic": "ترافیک",
    "nav.rep-support": "پشتیبانی",
    "nav.cms-pages": "صفحات",
    "nav.cms-builder": "صفحه‌ساز",
    "nav.cms-posts": "نوشته‌ها",
    "nav.cms-post-create": "نوشته جدید",
    "nav.cms-categories": "دسته‌ها",
    "nav.cms-tags": "برچسب‌ها",
    "nav.cms-comments": "دیدگاه‌ها",
    "nav.cms-media": "رسانه",
    "nav.profile-overview": "نمای کلی",
    "nav.profile-activity": "فعالیت‌ها",
    "nav.profile-projects": "پروژه‌ها",
    "nav.profile-invoices": "فاکتورها",
    "nav.profile-documents": "اسناد",
    "nav.profile-security": "امنیت",
    "nav.profile-sessions": "نشست‌های فعال",
    "nav.profile-keys": "کلیدهای API",
    "nav.profile-notifications": "اعلان‌ها",
    "nav.set-general": "عمومی",
    "nav.set-appearance": "ظاهر",
    "nav.set-layout": "چیدمان",
    "nav.set-localization": "بومی‌سازی",
    "nav.set-security": "امنیت",
    "nav.set-notifications": "اعلان‌ها",
    "nav.set-email": "ایمیل",
    "nav.set-integrations": "یکپارچه‌سازی",
    "nav.set-api": "API و وب‌هوک",
    "nav.set-billing": "صورتحساب",
    "nav.set-system": "سیستم",
    "nav.ui-buttons": "دکمه‌ها",
    "nav.ui-forms": "فرم‌ها",
    "nav.ui-inputs": "ورودی‌های پیشرفته",
    "nav.ui-cards": "کارت‌ها",
    "nav.ui-tables": "جدول‌ها",
    "nav.ui-badges": "نشان‌ها",
    "nav.ui-alerts": "هشدارها",
    "nav.ui-toasts": "توست‌ها",
    "nav.ui-modals": "مودال و دراور",
    "nav.ui-dropdowns": "منوهای بازشو",
    "nav.ui-tooltips": "تولتیپ و پاپ‌اور",
    "nav.ui-tabs": "تب و آکاردئون",
    "nav.ui-progress": "پیشرفت و اسپینر",
    "nav.ui-timeline": "خط زمان",
    "nav.ui-avatars": "آواتار",
    "nav.ui-charts": "نمودارها",
    "nav.ui-typography": "تایپوگرافی",
    "nav.ui-colors": "رنگ‌ها",
    "nav.ui-icons": "آیکون‌ها",
    "nav.ui-grid": "شبکه و فاصله",
    "nav.ui-states": "حالت‌های صفحه",
    "nav.doc-intro": "معرفی",
    "nav.doc-install": "نصب",
    "nav.doc-dev": "محیط توسعه",
    "nav.doc-build": "ساخت و انتشار",
    "nav.doc-structure": "ساختار پروژه",
    "nav.doc-config": "تنظیمات",
    "nav.doc-theme": "شخصی‌سازی تم",
    "nav.doc-rtl": "RTL و LTR",
    "nav.doc-i18n": "چندزبانه",
    "nav.doc-jalali": "تقویم شمسی",
    "nav.doc-components": "کامپوننت‌ها",
    "nav.doc-tables": "جدول داده",
    "nav.doc-forms": "فرم و اعتبارسنجی",
    "nav.doc-charts": "نمودارها",
    "nav.doc-adding": "افزودن صفحه جدید",
    "nav.doc-api": "اتصال به API",
    "nav.doc-auth": "احراز هویت",
    "nav.doc-laravel": "تبدیل به Laravel",
    "nav.doc-deploy": "استقرار در هاست",
    "nav.doc-faq": "پرسش‌های متداول",
    "nav.doc-troubleshoot": "رفع اشکال",
    "nav.doc-migration": "مهاجرت و به‌روزرسانی",
    "nav.doc-credits": "اعتبارها و مجوزها",
    "nav.sys-404": "۴۰۴ یافت نشد",
    "nav.sys-403": "۴۰۳ دسترسی",
    "nav.sys-500": "۵۰۰ خطای سرور",
    "nav.sys-maintenance": "در حال تعمیر",
    "nav.sys-coming": "به‌زودی",
    "nav.sys-offline": "آفلاین",
    "nav.sys-blank": "صفحه خالی",
    "nav.sys-search": "نتایج جستجو",
    "nav.sys-pricing": "تعرفه‌ها",
    "nav.sys-faq": "پرسش‌های متداول",
    "nav.sys-help": "مرکز راهنما",
    "nav.sys-contact": "تماس با ما",
    "nav.sys-status": "وضعیت سرویس",
    "nav.sys-changelog": "تغییرات نسخه",
    "nav.sys-terms": "قوانین",
    "nav.sys-privacy": "حریم خصوصی",
    "nav.auth-login": "ورود",
    "nav.auth-login-split": "ورود دو ستونی",
    "nav.auth-login-minimal": "ورود مینیمال",
    "nav.auth-register": "ثبت‌نام",
    "nav.auth-forgot": "فراموشی رمز",
    "nav.auth-reset": "بازیابی رمز",
    "nav.auth-verify": "تأیید ایمیل",
    "nav.auth-2fa": "ورود دو مرحله‌ای",
    "nav.auth-lock": "قفل صفحه",
    "nav.auth-logout": "خروج",
    "nav.preview-html": "پیش‌نمایش محصول",
    "nav.auth-error-html": "خطای ورود",
    "section.main": "اصلی",
    "section.applications": "اپلیکیشن‌ها",
    "section.users-access": "کاربران و دسترسی",
    "section.reports-content": "گزارش‌ها و محتوا",
    "section.account-settings": "حساب و تنظیمات",
    "section.developers": "توسعه‌دهندگان"
  },
  "en": {
    "nav.dash-analytics": "Analytics",
    "nav.dash-ecommerce": "eCommerce",
    "nav.dash-crm": "CRM",
    "nav.dash-saas": "SaaS",
    "nav.dash-finance": "Finance",
    "nav.dash-projects": "Projects",
    "nav.dash-hr": "HR",
    "nav.dash-support": "Support",
    "nav.dash-ai": "AI SaaS",
    "nav.dash-logistics": "Logistics",
    "nav.widgets": "Widgets",
    "nav.ai-dashboard": "AI Dashboard",
    "nav.ai-chat": "AI Chat",
    "nav.ai-writer": "AI Writer",
    "nav.ai-summarizer": "AI Summarizer",
    "nav.ai-repurposer": "Content Repurposer",
    "nav.ai-prompts": "Prompt Library",
    "nav.ai-scheduler": "AI Scheduler",
    "nav.ai-images": "AI Image Studio",
    "nav.ai-usage": "AI Usage",
    "nav.ai-models": "Models",
    "nav.ai-keys": "API Keys",
    "nav.ai-history": "AI History",
    "nav.ec-products": "Products",
    "nav.ec-grid": "Product Grid",
    "nav.ec-details": "Product Details",
    "nav.ec-create": "Create Product",
    "nav.ec-categories": "Categories",
    "nav.ec-brands": "Brands",
    "nav.ec-tags": "Tags",
    "nav.ec-inventory": "Inventory",
    "nav.ec-reviews": "Reviews",
    "nav.ec-coupons": "Coupons",
    "nav.ec-orders": "Orders",
    "nav.ec-order-details": "Order Details",
    "nav.crm-pipeline": "Deal Pipeline",
    "nav.crm-contacts": "Contacts",
    "nav.crm-companies": "Companies",
    "nav.crm-leads": "Leads",
    "nav.crm-deals": "Deals",
    "nav.crm-activities": "Activities",
    "nav.crm-contact-details-html": "Contact Details",
    "nav.crm-company-details-html": "Company Details",
    "nav.crm-deal-details-html": "Deal Details",
    "nav.crm-calls": "Calls",
    "nav.crm-meetings": "Meetings",
    "nav.crm-campaigns": "Campaigns",
    "nav.fin-overview": "Overview",
    "nav.fin-transactions": "Transactions",
    "nav.fin-accounts": "Accounts",
    "nav.fin-expenses": "Expenses",
    "nav.fin-income": "Income",
    "nav.fin-payments": "Payments",
    "nav.fin-invoices": "Invoices",
    "nav.fin-invoice-details": "Invoice Details",
    "nav.fin-subscriptions": "Subscriptions",
    "nav.fin-payouts": "Payouts",
    "nav.prj-list": "Projects",
    "nav.prj-details": "Project Details",
    "nav.prj-tasks": "Tasks",
    "nav.prj-kanban": "Kanban Board",
    "nav.prj-timeline": "Timeline",
    "nav.sup-tickets": "Tickets",
    "nav.sup-details": "Ticket Details",
    "nav.sup-agents": "Agents",
    "nav.sup-kb": "Knowledge Base",
    "nav.hr-employees": "Employees",
    "nav.hr-profile": "Employee Profile",
    "nav.hr-attendance": "Attendance",
    "nav.hr-leave": "Leave Requests",
    "nav.hr-payroll": "Payroll",
    "nav.hr-departments": "Departments",
    "nav.hr-recruitment": "Recruitment",
    "nav.log-shipments": "Shipments",
    "nav.log-tracking": "Live Tracking",
    "nav.log-drivers": "Drivers",
    "nav.log-warehouses": "Warehouses",
    "nav.chat": "Chat",
    "nav.email": "Email",
    "nav.calendar": "Calendar",
    "nav.files": "File Manager",
    "nav.media": "Media Library",
    "nav.notifications": "Notifications",
    "nav.users-list": "Users List",
    "nav.users-grid": "Users Grid",
    "nav.users-create": "Create User",
    "nav.users-details": "User Details",
    "nav.users-roles": "Roles",
    "nav.users-permissions": "Permissions",
    "nav.users-teams": "Teams",
    "nav.users-departments": "Departments",
    "nav.users-invitations": "Invitations",
    "nav.users-activity": "Activity Log",
    "nav.users-sessions": "Sessions",
    "nav.cust-list": "Customer List",
    "nav.cust-details": "Customer Details",
    "nav.cust-orders": "Customer Orders",
    "nav.cust-segments": "Segments",
    "nav.rep-sales": "Sales Report",
    "nav.rep-revenue": "Revenue Report",
    "nav.rep-customers": "Customers Report",
    "nav.rep-products": "Products Report",
    "nav.rep-finance": "Finance Report",
    "nav.rep-performance": "Performance",
    "nav.rep-traffic": "Traffic",
    "nav.rep-support": "Support Report",
    "nav.cms-pages": "Pages",
    "nav.cms-builder": "Page Builder",
    "nav.cms-posts": "Blog Posts",
    "nav.cms-post-create": "New Post",
    "nav.cms-categories": "Categories",
    "nav.cms-tags": "Tags",
    "nav.cms-comments": "Comments",
    "nav.cms-media": "Media",
    "nav.profile-overview": "Overview",
    "nav.profile-activity": "Activity",
    "nav.profile-projects": "Projects",
    "nav.profile-invoices": "Invoices",
    "nav.profile-documents": "Documents",
    "nav.profile-security": "Security",
    "nav.profile-sessions": "Active Sessions",
    "nav.profile-keys": "API Keys",
    "nav.profile-notifications": "Notifications",
    "nav.set-general": "General",
    "nav.set-appearance": "Appearance",
    "nav.set-layout": "Layout",
    "nav.set-localization": "Localization",
    "nav.set-security": "Security",
    "nav.set-notifications": "Notifications",
    "nav.set-email": "Email",
    "nav.set-integrations": "Integrations",
    "nav.set-api": "API & Webhooks",
    "nav.set-billing": "Billing",
    "nav.set-system": "System",
    "nav.ui-buttons": "Buttons",
    "nav.ui-forms": "Forms",
    "nav.ui-inputs": "Advanced Inputs",
    "nav.ui-cards": "Cards",
    "nav.ui-tables": "Tables",
    "nav.ui-badges": "Badges & Pills",
    "nav.ui-alerts": "Alerts",
    "nav.ui-toasts": "Toasts",
    "nav.ui-modals": "Modals & Drawers",
    "nav.ui-dropdowns": "Dropdowns",
    "nav.ui-tooltips": "Tooltips & Popovers",
    "nav.ui-tabs": "Tabs & Accordion",
    "nav.ui-progress": "Progress & Spinners",
    "nav.ui-timeline": "Timeline & Steps",
    "nav.ui-avatars": "Avatars",
    "nav.ui-charts": "Charts",
    "nav.ui-typography": "Typography",
    "nav.ui-colors": "Colors",
    "nav.ui-icons": "Icons",
    "nav.ui-grid": "Grid & Spacing",
    "nav.ui-states": "States",
    "nav.doc-intro": "Introduction",
    "nav.doc-install": "Installation",
    "nav.doc-dev": "Development",
    "nav.doc-build": "Build & Deploy",
    "nav.doc-structure": "Folder Structure",
    "nav.doc-config": "Configuration",
    "nav.doc-theme": "Theme Customization",
    "nav.doc-rtl": "RTL & LTR",
    "nav.doc-i18n": "Localization",
    "nav.doc-jalali": "Jalali Calendar",
    "nav.doc-components": "Components",
    "nav.doc-tables": "Data Tables",
    "nav.doc-forms": "Forms & Validation",
    "nav.doc-charts": "Charts",
    "nav.doc-adding": "Adding a Page",
    "nav.doc-api": "API Integration",
    "nav.doc-auth": "Authentication",
    "nav.doc-laravel": "Convert to Laravel",
    "nav.doc-deploy": "Deployment",
    "nav.doc-faq": "FAQ & Support",
    "nav.doc-troubleshoot": "Troubleshooting",
    "nav.doc-migration": "Migration & Updates",
    "nav.doc-credits": "Credits & Licenses",
    "nav.sys-404": "404 Not Found",
    "nav.sys-403": "403 Forbidden",
    "nav.sys-500": "500 Server Error",
    "nav.sys-maintenance": "Maintenance",
    "nav.sys-coming": "Coming Soon",
    "nav.sys-offline": "Offline",
    "nav.sys-blank": "Blank Page",
    "nav.sys-search": "Search Results",
    "nav.sys-pricing": "Pricing",
    "nav.sys-faq": "FAQ",
    "nav.sys-help": "Help Center",
    "nav.sys-contact": "Contact",
    "nav.sys-status": "Status Page",
    "nav.sys-changelog": "Changelog",
    "nav.sys-terms": "Terms",
    "nav.sys-privacy": "Privacy",
    "nav.auth-login": "Login",
    "nav.auth-login-split": "Login Split",
    "nav.auth-login-minimal": "Login Minimal",
    "nav.auth-register": "Register",
    "nav.auth-forgot": "Forgot Password",
    "nav.auth-reset": "Reset Password",
    "nav.auth-verify": "Verify Email",
    "nav.auth-2fa": "Two-Factor",
    "nav.auth-lock": "Lock Screen",
    "nav.auth-logout": "Logout",
    "nav.preview-html": "Product Preview",
    "nav.auth-error-html": "Auth Error",
    "section.main": "Main",
    "section.applications": "Applications",
    "section.users-access": "Users & Access",
    "section.reports-content": "Reports & Content",
    "section.account-settings": "Account & Settings",
    "section.developers": "Developers"
  },
  "ar": {
    "nav.dash-analytics": "التحليلات",
    "nav.dash-ecommerce": "التجارة الإلكترونية",
    "nav.dash-crm": "إدارة العملاء",
    "nav.dash-saas": "البرمجيات كخدمة",
    "nav.dash-finance": "المالية",
    "nav.dash-projects": "إدارة المشاريع",
    "nav.dash-hr": "الموارد البشرية",
    "nav.dash-support": "الدعم",
    "nav.dash-ai": "الذكاء الاصطناعي",
    "nav.dash-logistics": "اللوجستيات",
    "nav.widgets": "الودجات",
    "nav.ai-dashboard": "لوحة الذكاء",
    "nav.ai-chat": "المحادثة الذكية",
    "nav.ai-writer": "الكاتب الذكي",
    "nav.ai-summarizer": "الملخّص",
    "nav.ai-repurposer": "إعادة صياغة المحتوى",
    "nav.ai-prompts": "مكتبة الأوامر",
    "nav.ai-scheduler": "مجدول الذكاء",
    "nav.ai-images": "استوديو الصور",
    "nav.ai-usage": "الاستهلاك",
    "nav.ai-models": "النماذج",
    "nav.ai-keys": "مفاتيح API",
    "nav.ai-history": "سجل الذكاء",
    "nav.ec-products": "المنتجات",
    "nav.ec-grid": "شبكة المنتجات",
    "nav.ec-details": "تفاصيل المنتج",
    "nav.ec-create": "إضافة منتج",
    "nav.ec-categories": "الفئات",
    "nav.ec-brands": "العلامات",
    "nav.ec-tags": "الوسوم",
    "nav.ec-inventory": "المخزون",
    "nav.ec-reviews": "التقييمات",
    "nav.ec-coupons": "الكوبونات",
    "nav.ec-orders": "الطلبات",
    "nav.ec-order-details": "تفاصيل الطلب",
    "nav.crm-pipeline": "قمع الصفقات",
    "nav.crm-contacts": "جهات الاتصال",
    "nav.crm-companies": "الشركات",
    "nav.crm-leads": "العملاء المحتملون",
    "nav.crm-deals": "الصفقات",
    "nav.crm-activities": "الأنشطة",
    "nav.crm-contact-details-html": "تفاصيل جهة الاتصال",
    "nav.crm-company-details-html": "تفاصيل الشركة",
    "nav.crm-deal-details-html": "تفاصيل الصفقة",
    "nav.crm-calls": "المكالمات",
    "nav.crm-meetings": "الاجتماعات",
    "nav.crm-campaigns": "الحملات",
    "nav.fin-overview": "نظرة عامة",
    "nav.fin-transactions": "الحركات",
    "nav.fin-accounts": "الحسابات",
    "nav.fin-expenses": "المصروفات",
    "nav.fin-income": "الإيرادات",
    "nav.fin-payments": "المدفوعات",
    "nav.fin-invoices": "الفواتير",
    "nav.fin-invoice-details": "تفاصيل الفاتورة",
    "nav.fin-subscriptions": "الاشتراكات",
    "nav.fin-payouts": "المدفوعات الصادرة",
    "nav.prj-list": "قائمة المشاريع",
    "nav.prj-details": "تفاصيل المشروع",
    "nav.prj-tasks": "المهام",
    "nav.prj-kanban": "لوحة كانبان",
    "nav.prj-timeline": "الجدول الزمني",
    "nav.sup-tickets": "التذاكر",
    "nav.sup-details": "تفاصيل التذكرة",
    "nav.sup-agents": "الوكلاء",
    "nav.sup-kb": "قاعدة المعرفة",
    "nav.hr-employees": "الموظفون",
    "nav.hr-profile": "ملف الموظف",
    "nav.hr-attendance": "الحضور",
    "nav.hr-leave": "الإجازات",
    "nav.hr-payroll": "الرواتب",
    "nav.hr-departments": "الأقسام",
    "nav.hr-recruitment": "التوظيف",
    "nav.log-shipments": "الشحنات",
    "nav.log-tracking": "التتبع المباشر",
    "nav.log-drivers": "السائقون",
    "nav.log-warehouses": "المستودعات",
    "nav.chat": "المحادثة",
    "nav.email": "البريد",
    "nav.calendar": "التقويم",
    "nav.files": "إدارة الملفات",
    "nav.media": "مكتبة الوسائط",
    "nav.notifications": "الإشعارات",
    "nav.users-list": "قائمة المستخدمين",
    "nav.users-grid": "شبكة المستخدمين",
    "nav.users-create": "إضافة مستخدم",
    "nav.users-details": "تفاصيل المستخدم",
    "nav.users-roles": "الأدوار",
    "nav.users-permissions": "الأذونات",
    "nav.users-teams": "الفرق",
    "nav.users-departments": "الأقسام",
    "nav.users-invitations": "الدعوات",
    "nav.users-activity": "سجل النشاط",
    "nav.users-sessions": "الجلسات",
    "nav.cust-list": "قائمة العملاء",
    "nav.cust-details": "تفاصيل العميل",
    "nav.cust-orders": "طلبات العميل",
    "nav.cust-segments": "الشرائح",
    "nav.rep-sales": "تقرير المبيعات",
    "nav.rep-revenue": "تقرير الإيرادات",
    "nav.rep-customers": "تقرير العملاء",
    "nav.rep-products": "تقرير المنتجات",
    "nav.rep-finance": "التقرير المالي",
    "nav.rep-performance": "الأداء",
    "nav.rep-traffic": "الزيارات",
    "nav.rep-support": "تقرير الدعم",
    "nav.cms-pages": "الصفحات",
    "nav.cms-builder": "منشئ الصفحات",
    "nav.cms-posts": "المقالات",
    "nav.cms-post-create": "مقال جديد",
    "nav.cms-categories": "التصنيفات",
    "nav.cms-tags": "الوسوم",
    "nav.cms-comments": "التعليقات",
    "nav.cms-media": "الوسائط",
    "nav.profile-overview": "نظرة عامة",
    "nav.profile-activity": "النشاط",
    "nav.profile-projects": "المشاريع",
    "nav.profile-invoices": "الفواتير",
    "nav.profile-documents": "المستندات",
    "nav.profile-security": "الأمان",
    "nav.profile-sessions": "الجلسات النشطة",
    "nav.profile-keys": "مفاتيح API",
    "nav.profile-notifications": "الإشعارات",
    "nav.set-general": "عام",
    "nav.set-appearance": "المظهر",
    "nav.set-layout": "التخطيط",
    "nav.set-localization": "التوطين",
    "nav.set-security": "الأمان",
    "nav.set-notifications": "الإشعارات",
    "nav.set-email": "البريد",
    "nav.set-integrations": "التكاملات",
    "nav.set-api": "API والخطافات",
    "nav.set-billing": "الفوترة",
    "nav.set-system": "النظام",
    "nav.ui-buttons": "الأزرار",
    "nav.ui-forms": "النماذج",
    "nav.ui-inputs": "إدخالات متقدمة",
    "nav.ui-cards": "البطاقات",
    "nav.ui-tables": "الجداول",
    "nav.ui-badges": "الشارات",
    "nav.ui-alerts": "التنبيهات",
    "nav.ui-toasts": "الإشعارات المنبثقة",
    "nav.ui-modals": "النوافذ الجانبية",
    "nav.ui-dropdowns": "القوائم",
    "nav.ui-tooltips": "التلميحات",
    "nav.ui-tabs": "التبويب والأكورديون",
    "nav.ui-progress": "التقدم والمؤشرات",
    "nav.ui-timeline": "الخط الزمني",
    "nav.ui-avatars": "الصور الرمزية",
    "nav.ui-charts": "الرسوم البيانية",
    "nav.ui-typography": "الطباعة",
    "nav.ui-colors": "الألوان",
    "nav.ui-icons": "الأيقونات",
    "nav.ui-grid": "الشبكة والمسافات",
    "nav.ui-states": "الحالات",
    "nav.doc-intro": "مقدمة",
    "nav.doc-install": "التثبيت",
    "nav.doc-dev": "التطوير",
    "nav.doc-build": "البناء والنشر",
    "nav.doc-structure": "هيكل المجلدات",
    "nav.doc-config": "الإعدادات",
    "nav.doc-theme": "تخصيص المظهر",
    "nav.doc-rtl": "الاتجاه",
    "nav.doc-i18n": "التوطين",
    "nav.doc-jalali": "التقويم الهجري الشمسي",
    "nav.doc-components": "المكوّنات",
    "nav.doc-tables": "جداول البيانات",
    "nav.doc-forms": "النماذج والتحقق",
    "nav.doc-charts": "الرسوم",
    "nav.doc-adding": "إضافة صفحة",
    "nav.doc-api": "تكامل API",
    "nav.doc-auth": "المصادقة",
    "nav.doc-laravel": "التحويل إلى Laravel",
    "nav.doc-deploy": "النشر على الاستضافة",
    "nav.doc-faq": "الأسئلة الشائعة",
    "nav.doc-troubleshoot": "حل المشاكل",
    "nav.doc-migration": "الترقية والتحديث",
    "nav.doc-credits": "الحقوق والتراخيص",
    "nav.sys-404": "404",
    "nav.sys-403": "403",
    "nav.sys-500": "500",
    "nav.sys-maintenance": "الصيانة",
    "nav.sys-coming": "قريباً",
    "nav.sys-offline": "غير متصل",
    "nav.sys-blank": "صفحة فارغة",
    "nav.sys-search": "نتائج البحث",
    "nav.sys-pricing": "الأسعار",
    "nav.sys-faq": "الأسئلة",
    "nav.sys-help": "مركز المساعدة",
    "nav.sys-contact": "اتصل بنا",
    "nav.sys-status": "حالة الخدمة",
    "nav.sys-changelog": "سجل التغييرات",
    "nav.sys-terms": "الشروط",
    "nav.sys-privacy": "الخصوصية",
    "nav.auth-login": "تسجيل الدخول",
    "nav.auth-login-split": "دخول بعمودين",
    "nav.auth-login-minimal": "دخول مبسط",
    "nav.auth-register": "التسجيل",
    "nav.auth-forgot": "نسيت كلمة المرور",
    "nav.auth-reset": "استعادة كلمة المرور",
    "nav.auth-verify": "تحقق البريد",
    "nav.auth-2fa": "التحقق بخطوتين",
    "nav.auth-lock": "شاشة القفل",
    "nav.auth-logout": "خروج",
    "nav.preview-html": "معاينة المنتج",
    "nav.auth-error-html": "خطأ الدخول",
    "section.main": "الرئيسية",
    "section.applications": "التطبيقات",
    "section.users-access": "المستخدمون والصلاحيات",
    "section.reports-content": "التقارير والمحتوى",
    "section.account-settings": "الحساب والإعدادات",
    "section.developers": "المطورون"
  }
};

export const pageTitles = {
  "fa": {
    "dashboards/analytics.html": "آنالیتیکس",
    "dashboards/ecommerce.html": "فروشگاهی",
    "dashboards/crm.html": "مدیریت مشتریان",
    "dashboards/saas.html": "سرویس ابری",
    "dashboards/finance.html": "مالی",
    "dashboards/projects.html": "مدیریت پروژه",
    "dashboards/hr.html": "منابع انسانی",
    "dashboards/support.html": "پشتیبانی",
    "dashboards/ai.html": "هوش مصنوعی",
    "dashboards/logistics.html": "لجستیک",
    "widgets.html": "ابزارک‌ها",
    "ai/dashboard.html": "داشبورد AI",
    "ai/chat.html": "گفتگوی هوشمند",
    "ai/writer.html": "نویسنده هوشمند",
    "ai/summarizer.html": "خلاصه‌ساز",
    "ai/repurposer.html": "بازتولید محتوا",
    "ai/prompts.html": "کتابخانه پرامپت",
    "ai/scheduler.html": "زمان‌بند AI",
    "ai/images.html": "استودیو تصویر",
    "ai/usage.html": "مصرف و هزینه",
    "ai/models.html": "مدل‌ها",
    "ai/api-keys.html": "کلیدهای API",
    "ai/history.html": "تاریخچه AI",
    "ecommerce/products.html": "محصولات",
    "ecommerce/product-grid.html": "نمایش شبکه‌ای",
    "ecommerce/product-details.html": "جزئیات محصول",
    "ecommerce/product-create.html": "افزودن محصول",
    "ecommerce/categories.html": "دسته‌بندی‌ها",
    "ecommerce/brands.html": "برندها",
    "ecommerce/tags.html": "برچسب‌ها",
    "ecommerce/inventory.html": "موجودی انبار",
    "ecommerce/reviews.html": "دیدگاه‌ها",
    "ecommerce/coupons.html": "کدهای تخفیف",
    "ecommerce/orders.html": "سفارش‌ها",
    "ecommerce/order-details.html": "جزئیات سفارش",
    "crm/pipeline.html": "قیف فروش",
    "crm/contacts.html": "مخاطبین",
    "crm/companies.html": "شرکت‌ها",
    "crm/leads.html": "سرنخ‌ها",
    "crm/deals.html": "معاملات",
    "crm/activities.html": "فعالیت‌ها",
    "crm/contact-details.html": "جزئیات مخاطب",
    "crm/company-details.html": "جزئیات شرکت",
    "crm/deal-details.html": "جزئیات معامله",
    "crm/calls.html": "تماس‌ها",
    "crm/meetings.html": "جلسات",
    "crm/campaigns.html": "کمپین‌ها",
    "finance/overview.html": "نمای کلی",
    "finance/transactions.html": "تراکنش‌ها",
    "finance/accounts.html": "حساب‌ها",
    "finance/expenses.html": "هزینه‌ها",
    "finance/income.html": "درآمدها",
    "finance/payments.html": "پرداخت‌ها",
    "finance/invoices.html": "فاکتورها",
    "finance/invoice-details.html": "جزئیات فاکتور",
    "finance/subscriptions.html": "اشتراک‌ها",
    "finance/payouts.html": "تسویه‌ها",
    "projects/list.html": "لیست پروژه‌ها",
    "projects/details.html": "جزئیات پروژه",
    "projects/tasks.html": "وظایف",
    "projects/kanban.html": "کانبان",
    "projects/timeline.html": "خط زمان",
    "support/tickets.html": "تیکت‌ها",
    "support/ticket-details.html": "جزئیات تیکت",
    "support/agents.html": "کارشناسان",
    "support/knowledge-base.html": "پایگاه دانش",
    "hr/employees.html": "کارکنان",
    "hr/employee-profile.html": "پروفایل کارمند",
    "hr/attendance.html": "حضور و غیاب",
    "hr/leave.html": "مرخصی‌ها",
    "hr/payroll.html": "حقوق و دستمزد",
    "hr/departments.html": "دپارتمان‌ها",
    "hr/recruitment.html": "استخدام",
    "logistics/shipments.html": "محموله‌ها",
    "logistics/tracking.html": "رهگیری زنده",
    "logistics/drivers.html": "رانندگان",
    "logistics/warehouses.html": "انبارها",
    "apps/chat.html": "گفتگو",
    "apps/email.html": "ایمیل",
    "apps/calendar.html": "تقویم",
    "apps/file-manager.html": "مدیریت فایل",
    "apps/media-library.html": "کتابخانه رسانه",
    "apps/notifications.html": "اعلان‌ها",
    "users/list.html": "لیست کاربران",
    "users/grid.html": "نمایش شبکه‌ای",
    "users/create.html": "افزودن کاربر",
    "users/details.html": "پروفایل کاربر",
    "users/roles.html": "نقش‌ها",
    "users/permissions.html": "مجوزها",
    "users/teams.html": "تیم‌ها",
    "users/departments.html": "دپارتمان‌ها",
    "users/invitations.html": "دعوت‌نامه‌ها",
    "users/activity.html": "فعالیت کاربران",
    "users/sessions.html": "نشست‌ها",
    "customers/list.html": "لیست مشتریان",
    "customers/details.html": "پروفایل مشتری",
    "customers/orders.html": "سفارش‌های مشتری",
    "customers/segments.html": "بخش‌بندی",
    "reports/sales.html": "فروش",
    "reports/revenue.html": "درآمد",
    "reports/customers.html": "مشتریان",
    "reports/products.html": "محصولات",
    "reports/finance.html": "مالی",
    "reports/performance.html": "عملکرد",
    "reports/traffic.html": "ترافیک",
    "reports/support.html": "پشتیبانی",
    "cms/pages.html": "صفحات",
    "cms/page-builder.html": "صفحه‌ساز",
    "cms/posts.html": "نوشته‌ها",
    "cms/post-create.html": "نوشته جدید",
    "cms/categories.html": "دسته‌ها",
    "cms/tags.html": "برچسب‌ها",
    "cms/comments.html": "دیدگاه‌ها",
    "cms/media.html": "رسانه",
    "profile/overview.html": "نمای کلی",
    "profile/activity.html": "فعالیت‌ها",
    "profile/projects.html": "پروژه‌ها",
    "profile/invoices.html": "فاکتورها",
    "profile/documents.html": "اسناد",
    "profile/security.html": "امنیت",
    "profile/sessions.html": "نشست‌های فعال",
    "profile/api-keys.html": "کلیدهای API",
    "profile/notifications.html": "اعلان‌ها",
    "settings/general.html": "عمومی",
    "settings/appearance.html": "ظاهر",
    "settings/layout.html": "چیدمان",
    "settings/localization.html": "بومی‌سازی",
    "settings/security.html": "امنیت",
    "settings/notifications.html": "اعلان‌ها",
    "settings/email.html": "ایمیل",
    "settings/integrations.html": "یکپارچه‌سازی",
    "settings/api.html": "API و وب‌هوک",
    "settings/billing.html": "صورتحساب",
    "settings/system.html": "سیستم",
    "ui/buttons.html": "دکمه‌ها",
    "ui/forms.html": "فرم‌ها",
    "ui/inputs.html": "ورودی‌های پیشرفته",
    "ui/cards.html": "کارت‌ها",
    "ui/tables.html": "جدول‌ها",
    "ui/badges.html": "نشان‌ها",
    "ui/alerts.html": "هشدارها",
    "ui/toasts.html": "توست‌ها",
    "ui/modals.html": "مودال و دراور",
    "ui/dropdowns.html": "منوهای بازشو",
    "ui/tooltips.html": "تولتیپ و پاپ‌اور",
    "ui/tabs.html": "تب و آکاردئون",
    "ui/progress.html": "پیشرفت و اسپینر",
    "ui/timeline.html": "خط زمان",
    "ui/avatars.html": "آواتار",
    "ui/charts.html": "نمودارها",
    "ui/typography.html": "تایپوگرافی",
    "ui/colors.html": "رنگ‌ها",
    "ui/icons.html": "آیکون‌ها",
    "ui/grid.html": "شبکه و فاصله",
    "ui/states.html": "حالت‌های صفحه",
    "docs/introduction.html": "معرفی",
    "docs/installation.html": "نصب",
    "docs/development.html": "محیط توسعه",
    "docs/build-deploy.html": "ساخت و انتشار",
    "docs/folder-structure.html": "ساختار پروژه",
    "docs/configuration.html": "تنظیمات",
    "docs/theme-customization.html": "شخصی‌سازی تم",
    "docs/rtl-ltr.html": "RTL و LTR",
    "docs/localization.html": "چندزبانه",
    "docs/jalali-calendar.html": "تقویم شمسی",
    "docs/components.html": "کامپوننت‌ها",
    "docs/data-tables.html": "جدول داده",
    "docs/forms.html": "فرم و اعتبارسنجی",
    "docs/charts.html": "نمودارها",
    "docs/adding-pages.html": "افزودن صفحه جدید",
    "docs/api-integration.html": "اتصال به API",
    "docs/authentication.html": "احراز هویت",
    "docs/laravel.html": "تبدیل به Laravel",
    "docs/deployment.html": "استقرار در هاست",
    "docs/faq.html": "پرسش‌های متداول",
    "docs/troubleshooting.html": "رفع اشکال",
    "docs/migration.html": "مهاجرت و به‌روزرسانی",
    "docs/credits.html": "اعتبارها و مجوزها",
    "system/404.html": "۴۰۴ یافت نشد",
    "system/403.html": "۴۰۳ دسترسی",
    "system/500.html": "۵۰۰ خطای سرور",
    "system/maintenance.html": "در حال تعمیر",
    "system/coming-soon.html": "به‌زودی",
    "system/offline.html": "آفلاین",
    "system/blank.html": "صفحه خالی",
    "system/search-results.html": "نتایج جستجو",
    "system/pricing.html": "تعرفه‌ها",
    "system/faq.html": "پرسش‌های متداول",
    "system/help-center.html": "مرکز راهنما",
    "system/contact.html": "تماس با ما",
    "system/status.html": "وضعیت سرویس",
    "system/changelog.html": "تغییرات نسخه",
    "system/terms.html": "قوانین",
    "system/privacy.html": "حریم خصوصی",
    "auth/login.html": "ورود",
    "auth/login-split.html": "ورود دو ستونی",
    "auth/login-minimal.html": "ورود مینیمال",
    "auth/register.html": "ثبت‌نام",
    "auth/forgot-password.html": "فراموشی رمز",
    "auth/reset-password.html": "بازیابی رمز",
    "auth/verify-email.html": "تأیید ایمیل",
    "auth/two-factor.html": "ورود دو مرحله‌ای",
    "auth/lock-screen.html": "قفل صفحه",
    "auth/logout.html": "خروج",
    "preview.html": "پیش‌نمایش محصول",
    "auth/error.html": "خطای ورود"
  },
  "en": {
    "dashboards/analytics.html": "Analytics",
    "dashboards/ecommerce.html": "eCommerce",
    "dashboards/crm.html": "CRM",
    "dashboards/saas.html": "SaaS",
    "dashboards/finance.html": "Finance",
    "dashboards/projects.html": "Projects",
    "dashboards/hr.html": "HR",
    "dashboards/support.html": "Support",
    "dashboards/ai.html": "AI SaaS",
    "dashboards/logistics.html": "Logistics",
    "widgets.html": "Widgets",
    "ai/dashboard.html": "AI Dashboard",
    "ai/chat.html": "AI Chat",
    "ai/writer.html": "AI Writer",
    "ai/summarizer.html": "AI Summarizer",
    "ai/repurposer.html": "Content Repurposer",
    "ai/prompts.html": "Prompt Library",
    "ai/scheduler.html": "AI Scheduler",
    "ai/images.html": "AI Image Studio",
    "ai/usage.html": "AI Usage",
    "ai/models.html": "Models",
    "ai/api-keys.html": "API Keys",
    "ai/history.html": "AI History",
    "ecommerce/products.html": "Products",
    "ecommerce/product-grid.html": "Product Grid",
    "ecommerce/product-details.html": "Product Details",
    "ecommerce/product-create.html": "Create Product",
    "ecommerce/categories.html": "Categories",
    "ecommerce/brands.html": "Brands",
    "ecommerce/tags.html": "Tags",
    "ecommerce/inventory.html": "Inventory",
    "ecommerce/reviews.html": "Reviews",
    "ecommerce/coupons.html": "Coupons",
    "ecommerce/orders.html": "Orders",
    "ecommerce/order-details.html": "Order Details",
    "crm/pipeline.html": "Deal Pipeline",
    "crm/contacts.html": "Contacts",
    "crm/companies.html": "Companies",
    "crm/leads.html": "Leads",
    "crm/deals.html": "Deals",
    "crm/activities.html": "Activities",
    "crm/contact-details.html": "Contact Details",
    "crm/company-details.html": "Company Details",
    "crm/deal-details.html": "Deal Details",
    "crm/calls.html": "Calls",
    "crm/meetings.html": "Meetings",
    "crm/campaigns.html": "Campaigns",
    "finance/overview.html": "Overview",
    "finance/transactions.html": "Transactions",
    "finance/accounts.html": "Accounts",
    "finance/expenses.html": "Expenses",
    "finance/income.html": "Income",
    "finance/payments.html": "Payments",
    "finance/invoices.html": "Invoices",
    "finance/invoice-details.html": "Invoice Details",
    "finance/subscriptions.html": "Subscriptions",
    "finance/payouts.html": "Payouts",
    "projects/list.html": "Projects",
    "projects/details.html": "Project Details",
    "projects/tasks.html": "Tasks",
    "projects/kanban.html": "Kanban Board",
    "projects/timeline.html": "Timeline",
    "support/tickets.html": "Tickets",
    "support/ticket-details.html": "Ticket Details",
    "support/agents.html": "Agents",
    "support/knowledge-base.html": "Knowledge Base",
    "hr/employees.html": "Employees",
    "hr/employee-profile.html": "Employee Profile",
    "hr/attendance.html": "Attendance",
    "hr/leave.html": "Leave Requests",
    "hr/payroll.html": "Payroll",
    "hr/departments.html": "Departments",
    "hr/recruitment.html": "Recruitment",
    "logistics/shipments.html": "Shipments",
    "logistics/tracking.html": "Live Tracking",
    "logistics/drivers.html": "Drivers",
    "logistics/warehouses.html": "Warehouses",
    "apps/chat.html": "Chat",
    "apps/email.html": "Email",
    "apps/calendar.html": "Calendar",
    "apps/file-manager.html": "File Manager",
    "apps/media-library.html": "Media Library",
    "apps/notifications.html": "Notifications",
    "users/list.html": "Users List",
    "users/grid.html": "Users Grid",
    "users/create.html": "Create User",
    "users/details.html": "User Details",
    "users/roles.html": "Roles",
    "users/permissions.html": "Permissions",
    "users/teams.html": "Teams",
    "users/departments.html": "Departments",
    "users/invitations.html": "Invitations",
    "users/activity.html": "Activity Log",
    "users/sessions.html": "Sessions",
    "customers/list.html": "Customer List",
    "customers/details.html": "Customer Details",
    "customers/orders.html": "Customer Orders",
    "customers/segments.html": "Segments",
    "reports/sales.html": "Sales Report",
    "reports/revenue.html": "Revenue Report",
    "reports/customers.html": "Customers Report",
    "reports/products.html": "Products Report",
    "reports/finance.html": "Finance Report",
    "reports/performance.html": "Performance",
    "reports/traffic.html": "Traffic",
    "reports/support.html": "Support Report",
    "cms/pages.html": "Pages",
    "cms/page-builder.html": "Page Builder",
    "cms/posts.html": "Blog Posts",
    "cms/post-create.html": "New Post",
    "cms/categories.html": "Categories",
    "cms/tags.html": "Tags",
    "cms/comments.html": "Comments",
    "cms/media.html": "Media",
    "profile/overview.html": "Overview",
    "profile/activity.html": "Activity",
    "profile/projects.html": "Projects",
    "profile/invoices.html": "Invoices",
    "profile/documents.html": "Documents",
    "profile/security.html": "Security",
    "profile/sessions.html": "Active Sessions",
    "profile/api-keys.html": "API Keys",
    "profile/notifications.html": "Notifications",
    "settings/general.html": "General",
    "settings/appearance.html": "Appearance",
    "settings/layout.html": "Layout",
    "settings/localization.html": "Localization",
    "settings/security.html": "Security",
    "settings/notifications.html": "Notifications",
    "settings/email.html": "Email",
    "settings/integrations.html": "Integrations",
    "settings/api.html": "API & Webhooks",
    "settings/billing.html": "Billing",
    "settings/system.html": "System",
    "ui/buttons.html": "Buttons",
    "ui/forms.html": "Forms",
    "ui/inputs.html": "Advanced Inputs",
    "ui/cards.html": "Cards",
    "ui/tables.html": "Tables",
    "ui/badges.html": "Badges & Pills",
    "ui/alerts.html": "Alerts",
    "ui/toasts.html": "Toasts",
    "ui/modals.html": "Modals & Drawers",
    "ui/dropdowns.html": "Dropdowns",
    "ui/tooltips.html": "Tooltips & Popovers",
    "ui/tabs.html": "Tabs & Accordion",
    "ui/progress.html": "Progress & Spinners",
    "ui/timeline.html": "Timeline & Steps",
    "ui/avatars.html": "Avatars",
    "ui/charts.html": "Charts",
    "ui/typography.html": "Typography",
    "ui/colors.html": "Colors",
    "ui/icons.html": "Icons",
    "ui/grid.html": "Grid & Spacing",
    "ui/states.html": "States",
    "docs/introduction.html": "Introduction",
    "docs/installation.html": "Installation",
    "docs/development.html": "Development",
    "docs/build-deploy.html": "Build & Deploy",
    "docs/folder-structure.html": "Folder Structure",
    "docs/configuration.html": "Configuration",
    "docs/theme-customization.html": "Theme Customization",
    "docs/rtl-ltr.html": "RTL & LTR",
    "docs/localization.html": "Localization",
    "docs/jalali-calendar.html": "Jalali Calendar",
    "docs/components.html": "Components",
    "docs/data-tables.html": "Data Tables",
    "docs/forms.html": "Forms & Validation",
    "docs/charts.html": "Charts",
    "docs/adding-pages.html": "Adding a Page",
    "docs/api-integration.html": "API Integration",
    "docs/authentication.html": "Authentication",
    "docs/laravel.html": "Convert to Laravel",
    "docs/deployment.html": "Deployment",
    "docs/faq.html": "FAQ & Support",
    "docs/troubleshooting.html": "Troubleshooting",
    "docs/migration.html": "Migration & Updates",
    "docs/credits.html": "Credits & Licenses",
    "system/404.html": "404 Not Found",
    "system/403.html": "403 Forbidden",
    "system/500.html": "500 Server Error",
    "system/maintenance.html": "Maintenance",
    "system/coming-soon.html": "Coming Soon",
    "system/offline.html": "Offline",
    "system/blank.html": "Blank Page",
    "system/search-results.html": "Search Results",
    "system/pricing.html": "Pricing",
    "system/faq.html": "FAQ",
    "system/help-center.html": "Help Center",
    "system/contact.html": "Contact",
    "system/status.html": "Status Page",
    "system/changelog.html": "Changelog",
    "system/terms.html": "Terms",
    "system/privacy.html": "Privacy",
    "auth/login.html": "Login",
    "auth/login-split.html": "Login Split",
    "auth/login-minimal.html": "Login Minimal",
    "auth/register.html": "Register",
    "auth/forgot-password.html": "Forgot Password",
    "auth/reset-password.html": "Reset Password",
    "auth/verify-email.html": "Verify Email",
    "auth/two-factor.html": "Two-Factor",
    "auth/lock-screen.html": "Lock Screen",
    "auth/logout.html": "Logout",
    "preview.html": "Product Preview",
    "auth/error.html": "Auth Error"
  },
  "ar": {
    "dashboards/analytics.html": "التحليلات",
    "dashboards/ecommerce.html": "التجارة الإلكترونية",
    "dashboards/crm.html": "إدارة العملاء",
    "dashboards/saas.html": "البرمجيات كخدمة",
    "dashboards/finance.html": "المالية",
    "dashboards/projects.html": "إدارة المشاريع",
    "dashboards/hr.html": "الموارد البشرية",
    "dashboards/support.html": "الدعم",
    "dashboards/ai.html": "الذكاء الاصطناعي",
    "dashboards/logistics.html": "اللوجستيات",
    "widgets.html": "الودجات",
    "ai/dashboard.html": "لوحة الذكاء",
    "ai/chat.html": "المحادثة الذكية",
    "ai/writer.html": "الكاتب الذكي",
    "ai/summarizer.html": "الملخّص",
    "ai/repurposer.html": "إعادة صياغة المحتوى",
    "ai/prompts.html": "مكتبة الأوامر",
    "ai/scheduler.html": "مجدول الذكاء",
    "ai/images.html": "استوديو الصور",
    "ai/usage.html": "الاستهلاك",
    "ai/models.html": "النماذج",
    "ai/api-keys.html": "مفاتيح API",
    "ai/history.html": "سجل الذكاء",
    "ecommerce/products.html": "المنتجات",
    "ecommerce/product-grid.html": "شبكة المنتجات",
    "ecommerce/product-details.html": "تفاصيل المنتج",
    "ecommerce/product-create.html": "إضافة منتج",
    "ecommerce/categories.html": "الفئات",
    "ecommerce/brands.html": "العلامات",
    "ecommerce/tags.html": "الوسوم",
    "ecommerce/inventory.html": "المخزون",
    "ecommerce/reviews.html": "التقييمات",
    "ecommerce/coupons.html": "الكوبونات",
    "ecommerce/orders.html": "الطلبات",
    "ecommerce/order-details.html": "تفاصيل الطلب",
    "crm/pipeline.html": "قمع الصفقات",
    "crm/contacts.html": "جهات الاتصال",
    "crm/companies.html": "الشركات",
    "crm/leads.html": "العملاء المحتملون",
    "crm/deals.html": "الصفقات",
    "crm/activities.html": "الأنشطة",
    "crm/contact-details.html": "تفاصيل جهة الاتصال",
    "crm/company-details.html": "تفاصيل الشركة",
    "crm/deal-details.html": "تفاصيل الصفقة",
    "crm/calls.html": "المكالمات",
    "crm/meetings.html": "الاجتماعات",
    "crm/campaigns.html": "الحملات",
    "finance/overview.html": "نظرة عامة",
    "finance/transactions.html": "الحركات",
    "finance/accounts.html": "الحسابات",
    "finance/expenses.html": "المصروفات",
    "finance/income.html": "الإيرادات",
    "finance/payments.html": "المدفوعات",
    "finance/invoices.html": "الفواتير",
    "finance/invoice-details.html": "تفاصيل الفاتورة",
    "finance/subscriptions.html": "الاشتراكات",
    "finance/payouts.html": "المدفوعات الصادرة",
    "projects/list.html": "قائمة المشاريع",
    "projects/details.html": "تفاصيل المشروع",
    "projects/tasks.html": "المهام",
    "projects/kanban.html": "لوحة كانبان",
    "projects/timeline.html": "الجدول الزمني",
    "support/tickets.html": "التذاكر",
    "support/ticket-details.html": "تفاصيل التذكرة",
    "support/agents.html": "الوكلاء",
    "support/knowledge-base.html": "قاعدة المعرفة",
    "hr/employees.html": "الموظفون",
    "hr/employee-profile.html": "ملف الموظف",
    "hr/attendance.html": "الحضور",
    "hr/leave.html": "الإجازات",
    "hr/payroll.html": "الرواتب",
    "hr/departments.html": "الأقسام",
    "hr/recruitment.html": "التوظيف",
    "logistics/shipments.html": "الشحنات",
    "logistics/tracking.html": "التتبع المباشر",
    "logistics/drivers.html": "السائقون",
    "logistics/warehouses.html": "المستودعات",
    "apps/chat.html": "المحادثة",
    "apps/email.html": "البريد",
    "apps/calendar.html": "التقويم",
    "apps/file-manager.html": "إدارة الملفات",
    "apps/media-library.html": "مكتبة الوسائط",
    "apps/notifications.html": "الإشعارات",
    "users/list.html": "قائمة المستخدمين",
    "users/grid.html": "شبكة المستخدمين",
    "users/create.html": "إضافة مستخدم",
    "users/details.html": "تفاصيل المستخدم",
    "users/roles.html": "الأدوار",
    "users/permissions.html": "الأذونات",
    "users/teams.html": "الفرق",
    "users/departments.html": "الأقسام",
    "users/invitations.html": "الدعوات",
    "users/activity.html": "سجل النشاط",
    "users/sessions.html": "الجلسات",
    "customers/list.html": "قائمة العملاء",
    "customers/details.html": "تفاصيل العميل",
    "customers/orders.html": "طلبات العميل",
    "customers/segments.html": "الشرائح",
    "reports/sales.html": "تقرير المبيعات",
    "reports/revenue.html": "تقرير الإيرادات",
    "reports/customers.html": "تقرير العملاء",
    "reports/products.html": "تقرير المنتجات",
    "reports/finance.html": "التقرير المالي",
    "reports/performance.html": "الأداء",
    "reports/traffic.html": "الزيارات",
    "reports/support.html": "تقرير الدعم",
    "cms/pages.html": "الصفحات",
    "cms/page-builder.html": "منشئ الصفحات",
    "cms/posts.html": "المقالات",
    "cms/post-create.html": "مقال جديد",
    "cms/categories.html": "التصنيفات",
    "cms/tags.html": "الوسوم",
    "cms/comments.html": "التعليقات",
    "cms/media.html": "الوسائط",
    "profile/overview.html": "نظرة عامة",
    "profile/activity.html": "النشاط",
    "profile/projects.html": "المشاريع",
    "profile/invoices.html": "الفواتير",
    "profile/documents.html": "المستندات",
    "profile/security.html": "الأمان",
    "profile/sessions.html": "الجلسات النشطة",
    "profile/api-keys.html": "مفاتيح API",
    "profile/notifications.html": "الإشعارات",
    "settings/general.html": "عام",
    "settings/appearance.html": "المظهر",
    "settings/layout.html": "التخطيط",
    "settings/localization.html": "التوطين",
    "settings/security.html": "الأمان",
    "settings/notifications.html": "الإشعارات",
    "settings/email.html": "البريد",
    "settings/integrations.html": "التكاملات",
    "settings/api.html": "API والخطافات",
    "settings/billing.html": "الفوترة",
    "settings/system.html": "النظام",
    "ui/buttons.html": "الأزرار",
    "ui/forms.html": "النماذج",
    "ui/inputs.html": "إدخالات متقدمة",
    "ui/cards.html": "البطاقات",
    "ui/tables.html": "الجداول",
    "ui/badges.html": "الشارات",
    "ui/alerts.html": "التنبيهات",
    "ui/toasts.html": "الإشعارات المنبثقة",
    "ui/modals.html": "النوافذ الجانبية",
    "ui/dropdowns.html": "القوائم",
    "ui/tooltips.html": "التلميحات",
    "ui/tabs.html": "التبويب والأكورديون",
    "ui/progress.html": "التقدم والمؤشرات",
    "ui/timeline.html": "الخط الزمني",
    "ui/avatars.html": "الصور الرمزية",
    "ui/charts.html": "الرسوم البيانية",
    "ui/typography.html": "الطباعة",
    "ui/colors.html": "الألوان",
    "ui/icons.html": "الأيقونات",
    "ui/grid.html": "الشبكة والمسافات",
    "ui/states.html": "الحالات",
    "docs/introduction.html": "مقدمة",
    "docs/installation.html": "التثبيت",
    "docs/development.html": "التطوير",
    "docs/build-deploy.html": "البناء والنشر",
    "docs/folder-structure.html": "هيكل المجلدات",
    "docs/configuration.html": "الإعدادات",
    "docs/theme-customization.html": "تخصيص المظهر",
    "docs/rtl-ltr.html": "الاتجاه",
    "docs/localization.html": "التوطين",
    "docs/jalali-calendar.html": "التقويم الهجري الشمسي",
    "docs/components.html": "المكوّنات",
    "docs/data-tables.html": "جداول البيانات",
    "docs/forms.html": "النماذج والتحقق",
    "docs/charts.html": "الرسوم",
    "docs/adding-pages.html": "إضافة صفحة",
    "docs/api-integration.html": "تكامل API",
    "docs/authentication.html": "المصادقة",
    "docs/laravel.html": "التحويل إلى Laravel",
    "docs/deployment.html": "النشر على الاستضافة",
    "docs/faq.html": "الأسئلة الشائعة",
    "docs/troubleshooting.html": "حل المشاكل",
    "docs/migration.html": "الترقية والتحديث",
    "docs/credits.html": "الحقوق والتراخيص",
    "system/404.html": "404",
    "system/403.html": "403",
    "system/500.html": "500",
    "system/maintenance.html": "الصيانة",
    "system/coming-soon.html": "قريباً",
    "system/offline.html": "غير متصل",
    "system/blank.html": "صفحة فارغة",
    "system/search-results.html": "نتائج البحث",
    "system/pricing.html": "الأسعار",
    "system/faq.html": "الأسئلة",
    "system/help-center.html": "مركز المساعدة",
    "system/contact.html": "اتصل بنا",
    "system/status.html": "حالة الخدمة",
    "system/changelog.html": "سجل التغييرات",
    "system/terms.html": "الشروط",
    "system/privacy.html": "الخصوصية",
    "auth/login.html": "تسجيل الدخول",
    "auth/login-split.html": "دخول بعمودين",
    "auth/login-minimal.html": "دخول مبسط",
    "auth/register.html": "التسجيل",
    "auth/forgot-password.html": "نسيت كلمة المرور",
    "auth/reset-password.html": "استعادة كلمة المرور",
    "auth/verify-email.html": "تحقق البريد",
    "auth/two-factor.html": "التحقق بخطوتين",
    "auth/lock-screen.html": "شاشة القفل",
    "auth/logout.html": "خروج",
    "preview.html": "معاينة المنتج",
    "auth/error.html": "خطأ الدخول"
  }
};

export const pageMeta = {
  "dashboards/analytics.html": {
    "section": "main",
    "kind": "dashboard",
    "parents": [],
    "titleKey": "nav.dash-analytics"
  },
  "dashboards/ecommerce.html": {
    "section": "main",
    "kind": "dashboard",
    "parents": [
      {
        "id": "dashboards",
        "url": "dashboards/analytics.html"
      }
    ],
    "titleKey": "nav.dash-ecommerce"
  },
  "dashboards/crm.html": {
    "section": "main",
    "kind": "dashboard",
    "parents": [
      {
        "id": "dashboards",
        "url": "dashboards/analytics.html"
      }
    ],
    "titleKey": "nav.dash-crm"
  },
  "dashboards/saas.html": {
    "section": "main",
    "kind": "dashboard",
    "parents": [
      {
        "id": "dashboards",
        "url": "dashboards/analytics.html"
      }
    ],
    "titleKey": "nav.dash-saas"
  },
  "dashboards/finance.html": {
    "section": "main",
    "kind": "dashboard",
    "parents": [
      {
        "id": "dashboards",
        "url": "dashboards/analytics.html"
      }
    ],
    "titleKey": "nav.dash-finance"
  },
  "dashboards/projects.html": {
    "section": "main",
    "kind": "dashboard",
    "parents": [
      {
        "id": "dashboards",
        "url": "dashboards/analytics.html"
      }
    ],
    "titleKey": "nav.dash-projects"
  },
  "dashboards/hr.html": {
    "section": "main",
    "kind": "dashboard",
    "parents": [
      {
        "id": "dashboards",
        "url": "dashboards/analytics.html"
      }
    ],
    "titleKey": "nav.dash-hr"
  },
  "dashboards/support.html": {
    "section": "main",
    "kind": "dashboard",
    "parents": [
      {
        "id": "dashboards",
        "url": "dashboards/analytics.html"
      }
    ],
    "titleKey": "nav.dash-support"
  },
  "dashboards/ai.html": {
    "section": "main",
    "kind": "dashboard",
    "parents": [
      {
        "id": "dashboards",
        "url": "dashboards/analytics.html"
      }
    ],
    "titleKey": "nav.dash-ai"
  },
  "dashboards/logistics.html": {
    "section": "main",
    "kind": "dashboard",
    "parents": [
      {
        "id": "dashboards",
        "url": "dashboards/analytics.html"
      }
    ],
    "titleKey": "nav.dash-logistics"
  },
  "widgets.html": {
    "section": "main",
    "kind": "app",
    "parents": [],
    "titleKey": "nav.widgets"
  },
  "ai/dashboard.html": {
    "section": "applications",
    "kind": "app",
    "parents": [],
    "titleKey": "nav.ai-dashboard"
  },
  "ai/chat.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "ai",
        "url": "ai/dashboard.html"
      }
    ],
    "titleKey": "nav.ai-chat"
  },
  "ai/writer.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "ai",
        "url": "ai/dashboard.html"
      }
    ],
    "titleKey": "nav.ai-writer"
  },
  "ai/summarizer.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "ai",
        "url": "ai/dashboard.html"
      }
    ],
    "titleKey": "nav.ai-summarizer"
  },
  "ai/repurposer.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "ai",
        "url": "ai/dashboard.html"
      }
    ],
    "titleKey": "nav.ai-repurposer"
  },
  "ai/prompts.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "ai",
        "url": "ai/dashboard.html"
      }
    ],
    "titleKey": "nav.ai-prompts"
  },
  "ai/scheduler.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "ai",
        "url": "ai/dashboard.html"
      }
    ],
    "titleKey": "nav.ai-scheduler"
  },
  "ai/images.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "ai",
        "url": "ai/dashboard.html"
      }
    ],
    "titleKey": "nav.ai-images"
  },
  "ai/usage.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "ai",
        "url": "ai/dashboard.html"
      }
    ],
    "titleKey": "nav.ai-usage"
  },
  "ai/models.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "ai",
        "url": "ai/dashboard.html"
      }
    ],
    "titleKey": "nav.ai-models"
  },
  "ai/api-keys.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "ai",
        "url": "ai/dashboard.html"
      }
    ],
    "titleKey": "nav.ai-keys"
  },
  "ai/history.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "ai",
        "url": "ai/dashboard.html"
      }
    ],
    "titleKey": "nav.ai-history"
  },
  "ecommerce/products.html": {
    "section": "applications",
    "kind": "list",
    "parents": [],
    "titleKey": "nav.ec-products"
  },
  "ecommerce/product-grid.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "ecommerce",
        "url": "ecommerce/products.html"
      }
    ],
    "titleKey": "nav.ec-grid"
  },
  "ecommerce/product-details.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "ecommerce",
        "url": "ecommerce/products.html"
      }
    ],
    "titleKey": "nav.ec-details"
  },
  "ecommerce/product-create.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "ecommerce",
        "url": "ecommerce/products.html"
      }
    ],
    "titleKey": "nav.ec-create"
  },
  "ecommerce/categories.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "ecommerce",
        "url": "ecommerce/products.html"
      }
    ],
    "titleKey": "nav.ec-categories"
  },
  "ecommerce/brands.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "ecommerce",
        "url": "ecommerce/products.html"
      }
    ],
    "titleKey": "nav.ec-brands"
  },
  "ecommerce/tags.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "ecommerce",
        "url": "ecommerce/products.html"
      }
    ],
    "titleKey": "nav.ec-tags"
  },
  "ecommerce/inventory.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "ecommerce",
        "url": "ecommerce/products.html"
      }
    ],
    "titleKey": "nav.ec-inventory"
  },
  "ecommerce/reviews.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "ecommerce",
        "url": "ecommerce/products.html"
      }
    ],
    "titleKey": "nav.ec-reviews"
  },
  "ecommerce/coupons.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "ecommerce",
        "url": "ecommerce/products.html"
      }
    ],
    "titleKey": "nav.ec-coupons"
  },
  "ecommerce/orders.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "ecommerce",
        "url": "ecommerce/products.html"
      }
    ],
    "titleKey": "nav.ec-orders"
  },
  "ecommerce/order-details.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "ecommerce",
        "url": "ecommerce/products.html"
      }
    ],
    "titleKey": "nav.ec-order-details"
  },
  "crm/pipeline.html": {
    "section": "applications",
    "kind": "app",
    "parents": [],
    "titleKey": "nav.crm-pipeline"
  },
  "crm/contacts.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "crm",
        "url": "crm/pipeline.html"
      }
    ],
    "titleKey": "nav.crm-contacts"
  },
  "crm/companies.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "crm",
        "url": "crm/pipeline.html"
      }
    ],
    "titleKey": "nav.crm-companies"
  },
  "crm/leads.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "crm",
        "url": "crm/pipeline.html"
      }
    ],
    "titleKey": "nav.crm-leads"
  },
  "crm/deals.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "crm",
        "url": "crm/pipeline.html"
      }
    ],
    "titleKey": "nav.crm-deals"
  },
  "crm/activities.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "crm",
        "url": "crm/pipeline.html"
      }
    ],
    "titleKey": "nav.crm-activities"
  },
  "crm/contact-details.html": {
    "section": "app",
    "kind": "app",
    "parents": [],
    "titleKey": "nav.crm-contact-details-html"
  },
  "crm/company-details.html": {
    "section": "app",
    "kind": "app",
    "parents": [],
    "titleKey": "nav.crm-company-details-html"
  },
  "crm/deal-details.html": {
    "section": "app",
    "kind": "app",
    "parents": [],
    "titleKey": "nav.crm-deal-details-html"
  },
  "crm/calls.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "crm",
        "url": "crm/pipeline.html"
      }
    ],
    "titleKey": "nav.crm-calls"
  },
  "crm/meetings.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "crm",
        "url": "crm/pipeline.html"
      }
    ],
    "titleKey": "nav.crm-meetings"
  },
  "crm/campaigns.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "crm",
        "url": "crm/pipeline.html"
      }
    ],
    "titleKey": "nav.crm-campaigns"
  },
  "finance/overview.html": {
    "section": "applications",
    "kind": "app",
    "parents": [],
    "titleKey": "nav.fin-overview"
  },
  "finance/transactions.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "finance",
        "url": "finance/overview.html"
      }
    ],
    "titleKey": "nav.fin-transactions"
  },
  "finance/accounts.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "finance",
        "url": "finance/overview.html"
      }
    ],
    "titleKey": "nav.fin-accounts"
  },
  "finance/expenses.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "finance",
        "url": "finance/overview.html"
      }
    ],
    "titleKey": "nav.fin-expenses"
  },
  "finance/income.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "finance",
        "url": "finance/overview.html"
      }
    ],
    "titleKey": "nav.fin-income"
  },
  "finance/payments.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "finance",
        "url": "finance/overview.html"
      }
    ],
    "titleKey": "nav.fin-payments"
  },
  "finance/invoices.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "finance",
        "url": "finance/overview.html"
      }
    ],
    "titleKey": "nav.fin-invoices"
  },
  "finance/invoice-details.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "finance",
        "url": "finance/overview.html"
      }
    ],
    "titleKey": "nav.fin-invoice-details"
  },
  "finance/subscriptions.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "finance",
        "url": "finance/overview.html"
      }
    ],
    "titleKey": "nav.fin-subscriptions"
  },
  "finance/payouts.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "finance",
        "url": "finance/overview.html"
      }
    ],
    "titleKey": "nav.fin-payouts"
  },
  "projects/list.html": {
    "section": "applications",
    "kind": "app",
    "parents": [],
    "titleKey": "nav.prj-list"
  },
  "projects/details.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "projects",
        "url": "projects/list.html"
      }
    ],
    "titleKey": "nav.prj-details"
  },
  "projects/tasks.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "projects",
        "url": "projects/list.html"
      }
    ],
    "titleKey": "nav.prj-tasks"
  },
  "projects/kanban.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "projects",
        "url": "projects/list.html"
      }
    ],
    "titleKey": "nav.prj-kanban"
  },
  "projects/timeline.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "projects",
        "url": "projects/list.html"
      }
    ],
    "titleKey": "nav.prj-timeline"
  },
  "support/tickets.html": {
    "section": "applications",
    "kind": "list",
    "parents": [],
    "titleKey": "nav.sup-tickets"
  },
  "support/ticket-details.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "support",
        "url": "support/tickets.html"
      }
    ],
    "titleKey": "nav.sup-details"
  },
  "support/agents.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "support",
        "url": "support/tickets.html"
      }
    ],
    "titleKey": "nav.sup-agents"
  },
  "support/knowledge-base.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "support",
        "url": "support/tickets.html"
      }
    ],
    "titleKey": "nav.sup-kb"
  },
  "hr/employees.html": {
    "section": "applications",
    "kind": "list",
    "parents": [],
    "titleKey": "nav.hr-employees"
  },
  "hr/employee-profile.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "hr",
        "url": "hr/employees.html"
      }
    ],
    "titleKey": "nav.hr-profile"
  },
  "hr/attendance.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "hr",
        "url": "hr/employees.html"
      }
    ],
    "titleKey": "nav.hr-attendance"
  },
  "hr/leave.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "hr",
        "url": "hr/employees.html"
      }
    ],
    "titleKey": "nav.hr-leave"
  },
  "hr/payroll.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "hr",
        "url": "hr/employees.html"
      }
    ],
    "titleKey": "nav.hr-payroll"
  },
  "hr/departments.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "hr",
        "url": "hr/employees.html"
      }
    ],
    "titleKey": "nav.hr-departments"
  },
  "hr/recruitment.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "hr",
        "url": "hr/employees.html"
      }
    ],
    "titleKey": "nav.hr-recruitment"
  },
  "logistics/shipments.html": {
    "section": "applications",
    "kind": "list",
    "parents": [],
    "titleKey": "nav.log-shipments"
  },
  "logistics/tracking.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "logistics",
        "url": "logistics/shipments.html"
      }
    ],
    "titleKey": "nav.log-tracking"
  },
  "logistics/drivers.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "logistics",
        "url": "logistics/shipments.html"
      }
    ],
    "titleKey": "nav.log-drivers"
  },
  "logistics/warehouses.html": {
    "section": "applications",
    "kind": "list",
    "parents": [
      {
        "id": "logistics",
        "url": "logistics/shipments.html"
      }
    ],
    "titleKey": "nav.log-warehouses"
  },
  "apps/chat.html": {
    "section": "applications",
    "kind": "app",
    "parents": [],
    "titleKey": "nav.chat"
  },
  "apps/email.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "communication",
        "url": "apps/chat.html"
      }
    ],
    "titleKey": "nav.email"
  },
  "apps/calendar.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "communication",
        "url": "apps/chat.html"
      }
    ],
    "titleKey": "nav.calendar"
  },
  "apps/file-manager.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "communication",
        "url": "apps/chat.html"
      }
    ],
    "titleKey": "nav.files"
  },
  "apps/media-library.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "communication",
        "url": "apps/chat.html"
      }
    ],
    "titleKey": "nav.media"
  },
  "apps/notifications.html": {
    "section": "applications",
    "kind": "app",
    "parents": [
      {
        "id": "communication",
        "url": "apps/chat.html"
      }
    ],
    "titleKey": "nav.notifications"
  },
  "users/list.html": {
    "section": "users-access",
    "kind": "list",
    "parents": [],
    "titleKey": "nav.users-list"
  },
  "users/grid.html": {
    "section": "users-access",
    "kind": "app",
    "parents": [
      {
        "id": "users",
        "url": "users/list.html"
      }
    ],
    "titleKey": "nav.users-grid"
  },
  "users/create.html": {
    "section": "users-access",
    "kind": "app",
    "parents": [
      {
        "id": "users",
        "url": "users/list.html"
      }
    ],
    "titleKey": "nav.users-create"
  },
  "users/details.html": {
    "section": "users-access",
    "kind": "app",
    "parents": [
      {
        "id": "users",
        "url": "users/list.html"
      }
    ],
    "titleKey": "nav.users-details"
  },
  "users/roles.html": {
    "section": "users-access",
    "kind": "app",
    "parents": [
      {
        "id": "users",
        "url": "users/list.html"
      }
    ],
    "titleKey": "nav.users-roles"
  },
  "users/permissions.html": {
    "section": "users-access",
    "kind": "app",
    "parents": [
      {
        "id": "users",
        "url": "users/list.html"
      }
    ],
    "titleKey": "nav.users-permissions"
  },
  "users/teams.html": {
    "section": "users-access",
    "kind": "app",
    "parents": [
      {
        "id": "users",
        "url": "users/list.html"
      }
    ],
    "titleKey": "nav.users-teams"
  },
  "users/departments.html": {
    "section": "users-access",
    "kind": "list",
    "parents": [
      {
        "id": "users",
        "url": "users/list.html"
      }
    ],
    "titleKey": "nav.users-departments"
  },
  "users/invitations.html": {
    "section": "users-access",
    "kind": "list",
    "parents": [
      {
        "id": "users",
        "url": "users/list.html"
      }
    ],
    "titleKey": "nav.users-invitations"
  },
  "users/activity.html": {
    "section": "users-access",
    "kind": "app",
    "parents": [
      {
        "id": "users",
        "url": "users/list.html"
      }
    ],
    "titleKey": "nav.users-activity"
  },
  "users/sessions.html": {
    "section": "users-access",
    "kind": "list",
    "parents": [
      {
        "id": "users",
        "url": "users/list.html"
      }
    ],
    "titleKey": "nav.users-sessions"
  },
  "customers/list.html": {
    "section": "users-access",
    "kind": "list",
    "parents": [],
    "titleKey": "nav.cust-list"
  },
  "customers/details.html": {
    "section": "users-access",
    "kind": "app",
    "parents": [
      {
        "id": "customers",
        "url": "customers/list.html"
      }
    ],
    "titleKey": "nav.cust-details"
  },
  "customers/orders.html": {
    "section": "users-access",
    "kind": "list",
    "parents": [
      {
        "id": "customers",
        "url": "customers/list.html"
      }
    ],
    "titleKey": "nav.cust-orders"
  },
  "customers/segments.html": {
    "section": "users-access",
    "kind": "app",
    "parents": [
      {
        "id": "customers",
        "url": "customers/list.html"
      }
    ],
    "titleKey": "nav.cust-segments"
  },
  "reports/sales.html": {
    "section": "reports-content",
    "kind": "app",
    "parents": [],
    "titleKey": "nav.rep-sales"
  },
  "reports/revenue.html": {
    "section": "reports-content",
    "kind": "app",
    "parents": [
      {
        "id": "reports",
        "url": "reports/sales.html"
      }
    ],
    "titleKey": "nav.rep-revenue"
  },
  "reports/customers.html": {
    "section": "reports-content",
    "kind": "app",
    "parents": [
      {
        "id": "reports",
        "url": "reports/sales.html"
      }
    ],
    "titleKey": "nav.rep-customers"
  },
  "reports/products.html": {
    "section": "reports-content",
    "kind": "app",
    "parents": [
      {
        "id": "reports",
        "url": "reports/sales.html"
      }
    ],
    "titleKey": "nav.rep-products"
  },
  "reports/finance.html": {
    "section": "reports-content",
    "kind": "app",
    "parents": [
      {
        "id": "reports",
        "url": "reports/sales.html"
      }
    ],
    "titleKey": "nav.rep-finance"
  },
  "reports/performance.html": {
    "section": "reports-content",
    "kind": "app",
    "parents": [
      {
        "id": "reports",
        "url": "reports/sales.html"
      }
    ],
    "titleKey": "nav.rep-performance"
  },
  "reports/traffic.html": {
    "section": "reports-content",
    "kind": "app",
    "parents": [
      {
        "id": "reports",
        "url": "reports/sales.html"
      }
    ],
    "titleKey": "nav.rep-traffic"
  },
  "reports/support.html": {
    "section": "reports-content",
    "kind": "app",
    "parents": [
      {
        "id": "reports",
        "url": "reports/sales.html"
      }
    ],
    "titleKey": "nav.rep-support"
  },
  "cms/pages.html": {
    "section": "reports-content",
    "kind": "list",
    "parents": [],
    "titleKey": "nav.cms-pages"
  },
  "cms/page-builder.html": {
    "section": "reports-content",
    "kind": "app",
    "parents": [
      {
        "id": "cms",
        "url": "cms/pages.html"
      }
    ],
    "titleKey": "nav.cms-builder"
  },
  "cms/posts.html": {
    "section": "reports-content",
    "kind": "list",
    "parents": [
      {
        "id": "cms",
        "url": "cms/pages.html"
      }
    ],
    "titleKey": "nav.cms-posts"
  },
  "cms/post-create.html": {
    "section": "reports-content",
    "kind": "app",
    "parents": [
      {
        "id": "cms",
        "url": "cms/pages.html"
      }
    ],
    "titleKey": "nav.cms-post-create"
  },
  "cms/categories.html": {
    "section": "reports-content",
    "kind": "list",
    "parents": [
      {
        "id": "cms",
        "url": "cms/pages.html"
      }
    ],
    "titleKey": "nav.cms-categories"
  },
  "cms/tags.html": {
    "section": "reports-content",
    "kind": "list",
    "parents": [
      {
        "id": "cms",
        "url": "cms/pages.html"
      }
    ],
    "titleKey": "nav.cms-tags"
  },
  "cms/comments.html": {
    "section": "reports-content",
    "kind": "list",
    "parents": [
      {
        "id": "cms",
        "url": "cms/pages.html"
      }
    ],
    "titleKey": "nav.cms-comments"
  },
  "cms/media.html": {
    "section": "reports-content",
    "kind": "app",
    "parents": [
      {
        "id": "cms",
        "url": "cms/pages.html"
      }
    ],
    "titleKey": "nav.cms-media"
  },
  "profile/overview.html": {
    "section": "account-settings",
    "kind": "app",
    "parents": [],
    "titleKey": "nav.profile-overview"
  },
  "profile/activity.html": {
    "section": "account-settings",
    "kind": "app",
    "parents": [
      {
        "id": "profile",
        "url": "profile/overview.html"
      }
    ],
    "titleKey": "nav.profile-activity"
  },
  "profile/projects.html": {
    "section": "account-settings",
    "kind": "list",
    "parents": [
      {
        "id": "profile",
        "url": "profile/overview.html"
      }
    ],
    "titleKey": "nav.profile-projects"
  },
  "profile/invoices.html": {
    "section": "account-settings",
    "kind": "list",
    "parents": [
      {
        "id": "profile",
        "url": "profile/overview.html"
      }
    ],
    "titleKey": "nav.profile-invoices"
  },
  "profile/documents.html": {
    "section": "account-settings",
    "kind": "app",
    "parents": [
      {
        "id": "profile",
        "url": "profile/overview.html"
      }
    ],
    "titleKey": "nav.profile-documents"
  },
  "profile/security.html": {
    "section": "account-settings",
    "kind": "app",
    "parents": [
      {
        "id": "profile",
        "url": "profile/overview.html"
      }
    ],
    "titleKey": "nav.profile-security"
  },
  "profile/sessions.html": {
    "section": "account-settings",
    "kind": "list",
    "parents": [
      {
        "id": "profile",
        "url": "profile/overview.html"
      }
    ],
    "titleKey": "nav.profile-sessions"
  },
  "profile/api-keys.html": {
    "section": "account-settings",
    "kind": "app",
    "parents": [
      {
        "id": "profile",
        "url": "profile/overview.html"
      }
    ],
    "titleKey": "nav.profile-keys"
  },
  "profile/notifications.html": {
    "section": "account-settings",
    "kind": "app",
    "parents": [
      {
        "id": "profile",
        "url": "profile/overview.html"
      }
    ],
    "titleKey": "nav.profile-notifications"
  },
  "settings/general.html": {
    "section": "account-settings",
    "kind": "app",
    "parents": [],
    "titleKey": "nav.set-general"
  },
  "settings/appearance.html": {
    "section": "account-settings",
    "kind": "app",
    "parents": [
      {
        "id": "settings",
        "url": "settings/general.html"
      }
    ],
    "titleKey": "nav.set-appearance"
  },
  "settings/layout.html": {
    "section": "account-settings",
    "kind": "app",
    "parents": [
      {
        "id": "settings",
        "url": "settings/general.html"
      }
    ],
    "titleKey": "nav.set-layout"
  },
  "settings/localization.html": {
    "section": "account-settings",
    "kind": "app",
    "parents": [
      {
        "id": "settings",
        "url": "settings/general.html"
      }
    ],
    "titleKey": "nav.set-localization"
  },
  "settings/security.html": {
    "section": "account-settings",
    "kind": "app",
    "parents": [
      {
        "id": "settings",
        "url": "settings/general.html"
      }
    ],
    "titleKey": "nav.set-security"
  },
  "settings/notifications.html": {
    "section": "account-settings",
    "kind": "app",
    "parents": [
      {
        "id": "settings",
        "url": "settings/general.html"
      }
    ],
    "titleKey": "nav.set-notifications"
  },
  "settings/email.html": {
    "section": "account-settings",
    "kind": "app",
    "parents": [
      {
        "id": "settings",
        "url": "settings/general.html"
      }
    ],
    "titleKey": "nav.set-email"
  },
  "settings/integrations.html": {
    "section": "account-settings",
    "kind": "app",
    "parents": [
      {
        "id": "settings",
        "url": "settings/general.html"
      }
    ],
    "titleKey": "nav.set-integrations"
  },
  "settings/api.html": {
    "section": "account-settings",
    "kind": "app",
    "parents": [
      {
        "id": "settings",
        "url": "settings/general.html"
      }
    ],
    "titleKey": "nav.set-api"
  },
  "settings/billing.html": {
    "section": "account-settings",
    "kind": "app",
    "parents": [
      {
        "id": "settings",
        "url": "settings/general.html"
      }
    ],
    "titleKey": "nav.set-billing"
  },
  "settings/system.html": {
    "section": "account-settings",
    "kind": "app",
    "parents": [
      {
        "id": "settings",
        "url": "settings/general.html"
      }
    ],
    "titleKey": "nav.set-system"
  },
  "ui/buttons.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [],
    "titleKey": "nav.ui-buttons"
  },
  "ui/forms.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-forms"
  },
  "ui/inputs.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-inputs"
  },
  "ui/cards.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-cards"
  },
  "ui/tables.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-tables"
  },
  "ui/badges.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-badges"
  },
  "ui/alerts.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-alerts"
  },
  "ui/toasts.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-toasts"
  },
  "ui/modals.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-modals"
  },
  "ui/dropdowns.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-dropdowns"
  },
  "ui/tooltips.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-tooltips"
  },
  "ui/tabs.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-tabs"
  },
  "ui/progress.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-progress"
  },
  "ui/timeline.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-timeline"
  },
  "ui/avatars.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-avatars"
  },
  "ui/charts.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-charts"
  },
  "ui/typography.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-typography"
  },
  "ui/colors.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-colors"
  },
  "ui/icons.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-icons"
  },
  "ui/grid.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-grid"
  },
  "ui/states.html": {
    "section": "developers",
    "kind": "ui",
    "parents": [
      {
        "id": "ui",
        "url": "ui/buttons.html"
      }
    ],
    "titleKey": "nav.ui-states"
  },
  "docs/introduction.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [],
    "titleKey": "nav.doc-intro"
  },
  "docs/installation.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-install"
  },
  "docs/development.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-dev"
  },
  "docs/build-deploy.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-build"
  },
  "docs/folder-structure.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-structure"
  },
  "docs/configuration.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-config"
  },
  "docs/theme-customization.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-theme"
  },
  "docs/rtl-ltr.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-rtl"
  },
  "docs/localization.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-i18n"
  },
  "docs/jalali-calendar.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-jalali"
  },
  "docs/components.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-components"
  },
  "docs/data-tables.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-tables"
  },
  "docs/forms.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-forms"
  },
  "docs/charts.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-charts"
  },
  "docs/adding-pages.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-adding"
  },
  "docs/api-integration.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-api"
  },
  "docs/authentication.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-auth"
  },
  "docs/laravel.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-laravel"
  },
  "docs/deployment.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-deploy"
  },
  "docs/faq.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-faq"
  },
  "docs/troubleshooting.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-troubleshoot"
  },
  "docs/migration.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-migration"
  },
  "docs/credits.html": {
    "section": "developers",
    "kind": "doc",
    "parents": [
      {
        "id": "docs",
        "url": "docs/introduction.html"
      }
    ],
    "titleKey": "nav.doc-credits"
  },
  "system/404.html": {
    "section": "developers",
    "kind": "system",
    "parents": [],
    "titleKey": "nav.sys-404"
  },
  "system/403.html": {
    "section": "developers",
    "kind": "system",
    "parents": [
      {
        "id": "system",
        "url": "system/404.html"
      }
    ],
    "titleKey": "nav.sys-403"
  },
  "system/500.html": {
    "section": "developers",
    "kind": "system",
    "parents": [
      {
        "id": "system",
        "url": "system/404.html"
      }
    ],
    "titleKey": "nav.sys-500"
  },
  "system/maintenance.html": {
    "section": "developers",
    "kind": "system",
    "parents": [
      {
        "id": "system",
        "url": "system/404.html"
      }
    ],
    "titleKey": "nav.sys-maintenance"
  },
  "system/coming-soon.html": {
    "section": "developers",
    "kind": "system",
    "parents": [
      {
        "id": "system",
        "url": "system/404.html"
      }
    ],
    "titleKey": "nav.sys-coming"
  },
  "system/offline.html": {
    "section": "developers",
    "kind": "system",
    "parents": [
      {
        "id": "system",
        "url": "system/404.html"
      }
    ],
    "titleKey": "nav.sys-offline"
  },
  "system/blank.html": {
    "section": "developers",
    "kind": "system",
    "parents": [
      {
        "id": "system",
        "url": "system/404.html"
      }
    ],
    "titleKey": "nav.sys-blank"
  },
  "system/search-results.html": {
    "section": "developers",
    "kind": "system",
    "parents": [
      {
        "id": "system",
        "url": "system/404.html"
      }
    ],
    "titleKey": "nav.sys-search"
  },
  "system/pricing.html": {
    "section": "developers",
    "kind": "system",
    "parents": [
      {
        "id": "system",
        "url": "system/404.html"
      }
    ],
    "titleKey": "nav.sys-pricing"
  },
  "system/faq.html": {
    "section": "developers",
    "kind": "system",
    "parents": [
      {
        "id": "system",
        "url": "system/404.html"
      }
    ],
    "titleKey": "nav.sys-faq"
  },
  "system/help-center.html": {
    "section": "developers",
    "kind": "system",
    "parents": [
      {
        "id": "system",
        "url": "system/404.html"
      }
    ],
    "titleKey": "nav.sys-help"
  },
  "system/contact.html": {
    "section": "developers",
    "kind": "system",
    "parents": [
      {
        "id": "system",
        "url": "system/404.html"
      }
    ],
    "titleKey": "nav.sys-contact"
  },
  "system/status.html": {
    "section": "developers",
    "kind": "system",
    "parents": [
      {
        "id": "system",
        "url": "system/404.html"
      }
    ],
    "titleKey": "nav.sys-status"
  },
  "system/changelog.html": {
    "section": "developers",
    "kind": "system",
    "parents": [
      {
        "id": "system",
        "url": "system/404.html"
      }
    ],
    "titleKey": "nav.sys-changelog"
  },
  "system/terms.html": {
    "section": "developers",
    "kind": "system",
    "parents": [
      {
        "id": "system",
        "url": "system/404.html"
      }
    ],
    "titleKey": "nav.sys-terms"
  },
  "system/privacy.html": {
    "section": "developers",
    "kind": "system",
    "parents": [
      {
        "id": "system",
        "url": "system/404.html"
      }
    ],
    "titleKey": "nav.sys-privacy"
  },
  "auth/login.html": {
    "section": "developers",
    "kind": "auth",
    "parents": [],
    "titleKey": "nav.auth-login"
  },
  "auth/login-split.html": {
    "section": "developers",
    "kind": "auth",
    "parents": [
      {
        "id": "auth",
        "url": "auth/login.html"
      }
    ],
    "titleKey": "nav.auth-login-split"
  },
  "auth/login-minimal.html": {
    "section": "developers",
    "kind": "auth",
    "parents": [
      {
        "id": "auth",
        "url": "auth/login.html"
      }
    ],
    "titleKey": "nav.auth-login-minimal"
  },
  "auth/register.html": {
    "section": "developers",
    "kind": "auth",
    "parents": [
      {
        "id": "auth",
        "url": "auth/login.html"
      }
    ],
    "titleKey": "nav.auth-register"
  },
  "auth/forgot-password.html": {
    "section": "developers",
    "kind": "auth",
    "parents": [
      {
        "id": "auth",
        "url": "auth/login.html"
      }
    ],
    "titleKey": "nav.auth-forgot"
  },
  "auth/reset-password.html": {
    "section": "developers",
    "kind": "auth",
    "parents": [
      {
        "id": "auth",
        "url": "auth/login.html"
      }
    ],
    "titleKey": "nav.auth-reset"
  },
  "auth/verify-email.html": {
    "section": "developers",
    "kind": "auth",
    "parents": [
      {
        "id": "auth",
        "url": "auth/login.html"
      }
    ],
    "titleKey": "nav.auth-verify"
  },
  "auth/two-factor.html": {
    "section": "developers",
    "kind": "auth",
    "parents": [
      {
        "id": "auth",
        "url": "auth/login.html"
      }
    ],
    "titleKey": "nav.auth-2fa"
  },
  "auth/lock-screen.html": {
    "section": "developers",
    "kind": "auth",
    "parents": [
      {
        "id": "auth",
        "url": "auth/login.html"
      }
    ],
    "titleKey": "nav.auth-lock"
  },
  "auth/logout.html": {
    "section": "developers",
    "kind": "auth",
    "parents": [
      {
        "id": "auth",
        "url": "auth/login.html"
      }
    ],
    "titleKey": "nav.auth-logout"
  },
  "preview.html": {
    "section": "app",
    "kind": "app",
    "parents": [],
    "titleKey": "nav.preview-html"
  },
  "auth/error.html": {
    "section": "app",
    "kind": "auth",
    "parents": [],
    "titleKey": "nav.auth-error-html"
  }
};

export const docsOrder = [
  "docs/introduction.html",
  "docs/installation.html",
  "docs/development.html",
  "docs/build-deploy.html",
  "docs/folder-structure.html",
  "docs/configuration.html",
  "docs/theme-customization.html",
  "docs/rtl-ltr.html",
  "docs/localization.html",
  "docs/jalali-calendar.html",
  "docs/components.html",
  "docs/data-tables.html",
  "docs/forms.html",
  "docs/charts.html",
  "docs/adding-pages.html",
  "docs/api-integration.html",
  "docs/authentication.html",
  "docs/laravel.html",
  "docs/deployment.html",
  "docs/faq.html",
  "docs/troubleshooting.html",
  "docs/migration.html",
  "docs/credits.html"
];

export default { navLabels, pageTitles, pageMeta, docsOrder };
