/**
 * NOVAADMIN — column registry
 * ------------------------------------------------------------------
 * One place that knows how every resource is laid out in a data table. Both
 * the generic page renderer and the DataTable component read from here, so a
 * table whose markup ships with an empty <thead> still gets proper columns.
 */
export const COLUMNS = {
  calls: [
    { key: 'contact', label: 'مخاطب', type: 'primary', sub: 'company', sortable: true },
    { key: 'direction', label: 'نوع تماس', type: 'badge' },
    { key: 'duration', label: 'مدت مکالمه', type: 'text', sortable: true },
    { key: 'owner', label: 'کارشناس' },
    { key: 'at', label: 'زمان تماس', type: 'relative', sortable: true },
    { key: 'notes', label: 'یادداشت', type: 'text' },
    { key: 'status', label: 'نتیجه', type: 'badge', sortable: true },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  meetings: [
    { key: 'title', label: 'جلسه', type: 'primary', sub: 'with', sortable: true },
    { key: 'startsAt', label: 'زمان شروع', type: 'datetime', sortable: true },
    { key: 'duration', label: 'مدت (دقیقه)', type: 'number', align: 'end' },
    { key: 'location', label: 'محل برگزاری' },
    { key: 'attendees', label: 'شرکت‌کنندگان', type: 'number', align: 'end' },
    { key: 'status', label: 'وضعیت', type: 'badge', sortable: true },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  categories: [
    { key: 'name', label: 'دسته‌بندی', type: 'primary', sub: 'slug', sortable: true },
    { key: 'parent', label: 'دسته والد' },
    { key: 'products', label: 'محصولات', type: 'number', align: 'end', sortable: true },
    { key: 'revenue', label: 'درآمد', type: 'currency', align: 'end', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge', sortable: true },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  brands: [
    { key: 'name', label: 'برند', type: 'primary', sub: 'country', avatar: 'logo', sortable: true },
    { key: 'products', label: 'محصولات', type: 'number', align: 'end', sortable: true },
    { key: 'rating', label: 'امتیاز', type: 'rating', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge', sortable: true },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  tags: [
    { key: 'name', label: 'برچسب', type: 'swatch', sortable: true },
    { key: 'products', label: 'محصولات مرتبط', type: 'number', align: 'end', sortable: true },
    { key: 'color', label: 'رنگ', type: 'color' },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  accounts: [
    { key: 'name', label: 'حساب', type: 'primary', sub: 'bank', sortable: true },
    { key: 'number', label: 'شماره حساب' },
    { key: 'type', label: 'نوع' },
    { key: 'balance', label: 'موجودی', type: 'currency', align: 'end', sortable: true },
    { key: 'change', label: 'تغییر ماهانه', type: 'percent', raw: true, align: 'end' },
    { key: 'status', label: 'وضعیت', type: 'badge' },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  income: [
    { key: 'source', label: 'منبع درآمد', type: 'primary', sub: 'customer', sortable: true },
    { key: 'amount', label: 'مبلغ', type: 'currency', align: 'end', sortable: true },
    { key: 'method', label: 'روش' },
    { key: 'recurring', label: 'تکرارشونده', type: 'boolean' },
    { key: 'at', label: 'تاریخ', type: 'date', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge' },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  payments: [
    { key: 'reference', label: 'کد پیگیری', type: 'primary', sub: 'invoice', sortable: true },
    { key: 'customer', label: 'مشتری' },
    { key: 'gateway', label: 'درگاه' },
    { key: 'amount', label: 'مبلغ', type: 'currency', align: 'end', sortable: true },
    { key: 'at', label: 'تاریخ', type: 'relative', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge' },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  payouts: [
    { key: 'reference', label: 'کد تسویه', type: 'primary', sub: 'vendor', sortable: true },
    { key: 'amount', label: 'مبلغ', type: 'currency', align: 'end', sortable: true },
    { key: 'fee', label: 'کارمزد', type: 'currency', align: 'end' },
    { key: 'method', label: 'روش' },
    { key: 'at', label: 'تاریخ', type: 'date', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge' },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  agents: [
    { key: 'name', label: 'کارشناس', type: 'primary', sub: 'email', avatar: 'avatar', sortable: true },
    { key: 'team', label: 'تیم' },
    { key: 'openTickets', label: 'تیکت باز', type: 'number', align: 'end', sortable: true },
    { key: 'resolved', label: 'حل‌شده', type: 'number', align: 'end', sortable: true },
    { key: 'csat', label: 'رضایت', type: 'progress', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge' },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  leave: [
    { key: 'employee', label: 'کارمند', type: 'primary', sub: 'department', avatar: 'avatar', sortable: true },
    { key: 'type', label: 'نوع مرخصی' },
    { key: 'from', label: 'از', type: 'date' },
    { key: 'to', label: 'تا', type: 'date' },
    { key: 'days', label: 'روزها', type: 'number', align: 'end', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge' },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  payroll: [
    { key: 'employee', label: 'کارمند', type: 'primary', sub: 'department', avatar: 'avatar', sortable: true },
    { key: 'base', label: 'حقوق پایه', type: 'currency', align: 'end', sortable: true },
    { key: 'bonus', label: 'پاداش', type: 'currency', align: 'end' },
    { key: 'deductions', label: 'کسورات', type: 'currency', align: 'end' },
    { key: 'net', label: 'خالص پرداختی', type: 'currency', align: 'end', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge' },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  activities: [
    { key: 'subject', label: 'فعالیت', type: 'primary', sub: 'related', sortable: true },
    { key: 'type', label: 'نوع', type: 'badge' },
    { key: 'owner', label: 'مسئول' },
    { key: 'duration', label: 'مدت (دقیقه)', type: 'number', align: 'end' },
    { key: 'at', label: 'زمان', type: 'relative', sortable: true },
    { key: 'outcome', label: 'نتیجه' },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  crmActivity: [
    { key: 'subject', label: 'فعالیت', type: 'primary', sub: 'related', sortable: true },
    { key: 'type', label: 'نوع', type: 'badge' },
    { key: 'owner', label: 'مسئول' },
    { key: 'at', label: 'زمان', type: 'relative', sortable: true },
    { key: 'outcome', label: 'نتیجه' },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  posts: [
    { key: 'title', label: 'نوشته', type: 'primary', sub: 'author', sortable: true },
    { key: 'category', label: 'دسته‌بندی' },
    { key: 'views', label: 'بازدید', type: 'number', align: 'end', sortable: true },
    { key: 'comments', label: 'دیدگاه', type: 'number', align: 'end' },
    { key: 'publishedAt', label: 'انتشار', type: 'date', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge' },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  pages: [
    { key: 'title', label: 'صفحه', type: 'primary', sub: 'slug', sortable: true },
    { key: 'template', label: 'قالب' },
    { key: 'author', label: 'نویسنده' },
    { key: 'views', label: 'بازدید', type: 'number', align: 'end', sortable: true },
    { key: 'updatedAt', label: 'به‌روزرسانی', type: 'relative', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge' },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  comments: [
    { key: 'author', label: 'نویسنده', type: 'primary', sub: 'email', avatar: 'avatar', sortable: true },
    { key: 'text', label: 'متن دیدگاه', type: 'clamp' },
    { key: 'post', label: 'مطلب' },
    { key: 'at', label: 'زمان', type: 'relative', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge' },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  apiKeys: [
    { key: 'name', label: 'کلید', type: 'primary', sub: 'token', sortable: true },
    { key: 'scopes', label: 'دسترسی‌ها', type: 'tags' },
    { key: 'createdAt', label: 'ایجاد', type: 'date', sortable: true },
    { key: 'lastUsed', label: 'آخرین استفاده', type: 'relative' },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],

  orders: [
    { key: 'number', label: 'شماره سفارش', type: 'primary', sub: 'customer', sortable: true },
    { key: 'placedAt', label: 'تاریخ ثبت', type: 'relative', sortable: true },
    { key: 'itemsCount', label: 'اقلام', type: 'number', align: 'end' },
    { key: 'total', label: 'مبلغ کل', type: 'currency', align: 'end', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge', sortable: true },
    { key: 'payment', label: 'روش پرداخت' },
    { key: 'actions', label: 'عملیات', type: 'actions', href: 'ecommerce/order-details.html?id={id}' },
  ],
  products: [
    { key: 'name', label: 'محصول', type: 'primary', sub: 'sku', avatar: 'image', sortable: true },
    { key: 'category', label: 'دسته‌بندی' },
    { key: 'brand', label: 'برند' },
    { key: 'finalPrice', label: 'قیمت', type: 'currency', align: 'end', sortable: true },
    { key: 'stock', label: 'موجودی', type: 'number', align: 'end', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge', sortable: true },
    { key: 'actions', label: 'عملیات', type: 'actions', href: 'ecommerce/product-details.html?id={id}' },
  ],
  users: [
    { key: 'name', label: 'کاربر', type: 'primary', sub: 'email', avatar: 'avatar', sortable: true },
    { key: 'roleLabel', label: 'نقش' },
    { key: 'team', label: 'تیم' },
    { key: 'lastActive', label: 'آخرین فعالیت', type: 'relative', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge', sortable: true },
    { key: 'actions', label: 'عملیات', type: 'actions', href: 'users/details.html?id={id}' },
  ],
  customers: [
    { key: 'company', label: 'مشتری', type: 'primary', sub: 'contact', avatar: 'avatar', sortable: true },
    { key: 'plan', label: 'پلن' },
    { key: 'orders', label: 'سفارش‌ها', type: 'number', align: 'end', sortable: true },
    { key: 'totalSpend', label: 'مجموع خرید', type: 'currency', align: 'end', sortable: true },
    { key: 'satisfaction', label: 'رضایت', type: 'rating' },
    { key: 'status', label: 'وضعیت', type: 'badge' },
    { key: 'actions', label: 'عملیات', type: 'actions', href: 'customers/details.html?id={id}' },
  ],
  invoices: [
    { key: 'number', label: 'شماره فاکتور', type: 'primary', sub: 'customer', sortable: true },
    { key: 'issuedAt', label: 'تاریخ صدور', type: 'date', sortable: true },
    { key: 'dueAt', label: 'سررسید', type: 'date' },
    { key: 'total', label: 'مبلغ', type: 'currency', align: 'end', sortable: true },
    { key: 'paid', label: 'پرداخت‌شده', type: 'currency', align: 'end' },
    { key: 'status', label: 'وضعیت', type: 'badge', sortable: true },
    { key: 'actions', label: 'عملیات', type: 'actions', href: 'finance/invoice-details.html?id={id}' },
  ],
  transactions: [
    { key: 'reference', label: 'کد پیگیری', type: 'primary', sub: 'counterparty', sortable: true },
    { key: 'account', label: 'حساب' },
    { key: 'typeLabel', label: 'نوع' },
    { key: 'amount', label: 'مبلغ', type: 'currency', align: 'end', sortable: true },
    { key: 'method', label: 'روش' },
    { key: 'at', label: 'تاریخ', type: 'relative', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge' },
  ],
  tickets: [
    { key: 'number', label: 'شماره', type: 'primary', sub: 'subject', sortable: true },
    { key: 'customer', label: 'مشتری' },
    { key: 'category', label: 'دسته' },
    { key: 'priority', label: 'اولویت', type: 'badge', sortable: true },
    { key: 'agent', label: 'پشتیبان' },
    { key: 'createdAt', label: 'ایجاد', type: 'relative', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge', sortable: true },
    { key: 'actions', label: 'عملیات', type: 'actions', href: 'support/ticket-details.html?id={id}' },
  ],
  employees: [
    { key: 'name', label: 'کارمند', type: 'primary', sub: 'position', avatar: 'avatar', sortable: true },
    { key: 'department', label: 'دپارتمان' },
    { key: 'type', label: 'نوع همکاری' },
    { key: 'hiredAt', label: 'تاریخ استخدام', type: 'date', sortable: true },
    { key: 'performance', label: 'عملکرد', type: 'rating' },
    { key: 'status', label: 'وضعیت', type: 'badge' },
    { key: 'actions', label: 'عملیات', type: 'actions', href: 'hr/employee-profile.html?id={id}' },
  ],
  shipments: [
    { key: 'tracking', label: 'کد رهگیری', type: 'primary', sub: 'order', sortable: true },
    { key: 'destination', label: 'مقصد' },
    { key: 'carrier', label: 'شرکت حمل' },
    { key: 'driver', label: 'راننده', avatar: 'driverAvatar', type: 'primary' },
    { key: 'eta', label: 'زمان تخمینی', type: 'date' },
    { key: 'progress', label: 'پیشرفت', type: 'progress' },
    { key: 'status', label: 'وضعیت', type: 'badge', sortable: true },
  ],
  projects: [
    { key: 'name', label: 'پروژه', type: 'primary', sub: 'client', sortable: true },
    { key: 'team', label: 'تیم' },
    { key: 'owner', label: 'مدیر پروژه' },
    { key: 'progress', label: 'پیشرفت', type: 'progress', sortable: true },
    { key: 'budget', label: 'بودجه', type: 'currency', align: 'end', sortable: true },
    { key: 'dueDate', label: 'موعد', type: 'date', sortable: true },
    { key: 'actions', label: 'عملیات', type: 'actions', href: 'projects/details.html?id={id}' },
  ],
  tasks: [
    { key: 'title', label: 'تسک', type: 'primary', sub: 'project', sortable: true },
    { key: 'assignee', label: 'مسئول', avatar: 'assigneeAvatar', type: 'primary' },
    { key: 'priorityLabel', label: 'اولویت', type: 'badge', sortable: true },
    { key: 'dueDate', label: 'موعد', type: 'date', sortable: true },
    { key: 'progress', label: 'پیشرفت', type: 'progress' },
    { key: 'statusLabel', label: 'وضعیت', type: 'badge', sortable: true },
  ],
  deals: [
    { key: 'title', label: 'معامله', type: 'primary', sub: 'company', sortable: true },
    { key: 'owner', label: 'کارشناس', avatar: 'ownerAvatar', type: 'primary' },
    { key: 'value', label: 'ارزش', type: 'currency', align: 'end', sortable: true },
    { key: 'probability', label: 'احتمال', type: 'progress', sortable: true },
    { key: 'expectedClose', label: 'بستن مورد انتظار', type: 'date', sortable: true },
    { key: 'stageLabel', label: 'مرحله', type: 'badge', sortable: true },
    { key: 'actions', label: 'عملیات', type: 'actions', href: 'crm/deal-details.html?id={id}' },
  ],
  companies: [
    { key: 'name', label: 'شرکت', type: 'primary', sub: 'industry', avatar: 'logo', sortable: true },
    { key: 'city', label: 'شهر' },
    { key: 'employees', label: 'کارکنان', type: 'number', align: 'end', sortable: true },
    { key: 'openValue', label: 'فرصت باز', type: 'currency', align: 'end', sortable: true },
    { key: 'owner', label: 'کارشناس' },
    { key: 'status', label: 'وضعیت', type: 'badge' },
    { key: 'actions', label: 'عملیات', type: 'actions', href: 'crm/company-details.html?id={id}' },
  ],
  contacts: [
    { key: 'name', label: 'مخاطب', type: 'primary', sub: 'title', avatar: 'avatar', sortable: true },
    { key: 'company', label: 'شرکت' },
    { key: 'phone', label: 'تلفن' },
    { key: 'lastContact', label: 'آخرین تماس', type: 'relative', sortable: true },
    { key: 'value', label: 'ارزش', type: 'currency', align: 'end', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge' },
    { key: 'actions', label: 'عملیات', type: 'actions', href: 'crm/contact-details.html?id={id}' },
  ],
  leads: [
    { key: 'name', label: 'سرنخ', type: 'primary', sub: 'company', sortable: true },
    { key: 'source', label: 'منبع' },
    { key: 'score', label: 'امتیاز', type: 'progress', sortable: true },
    { key: 'estimatedValue', label: 'ارزش تخمینی', type: 'currency', align: 'end', sortable: true },
    { key: 'owner', label: 'کارشناس' },
    { key: 'status', label: 'وضعیت', type: 'badge' },
  ],
  'hr/leave': [
    { key: 'employee', label: 'کارمند', type: 'primary', sub: 'department', avatar: 'avatar', sortable: true },
    { key: 'type', label: 'نوع مرخصی' },
    { key: 'from', label: 'از', type: 'date' },
    { key: 'to', label: 'تا', type: 'date' },
    { key: 'days', label: 'روزها', type: 'number', align: 'end', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge' },
  ],
  campaigns: [
    { key: 'name', label: 'کمپین', type: 'primary', sub: 'channel', sortable: true },
    { key: 'budget', label: 'بودجه', type: 'currency', align: 'end', sortable: true },
    { key: 'spent', label: 'هزینه‌شده', type: 'currency', align: 'end' },
    { key: 'leads', label: 'سرنخ', type: 'number', align: 'end', sortable: true },
    { key: 'revenue', label: 'درآمد', type: 'currency', align: 'end', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge' },
  ],
  expenses: [
    { key: 'title', label: 'شرح', type: 'primary', sub: 'vendor', sortable: true },
    { key: 'category', label: 'دسته' },
    { key: 'amount', label: 'مبلغ', type: 'currency', align: 'end', sortable: true },
    { key: 'at', label: 'تاریخ', type: 'date', sortable: true },
    { key: 'owner', label: 'ثبت‌کننده' },
    { key: 'status', label: 'وضعیت', type: 'badge' },
  ],
  subscriptions: [
    { key: 'customer', label: 'مشتری', type: 'primary', sub: 'plan', avatar: 'avatar', sortable: true },
    { key: 'seats', label: 'کاربر', type: 'number', align: 'end' },
    { key: 'mrr', label: 'درآمد ماهانه', type: 'currency', align: 'end', sortable: true },
    { key: 'renewsAt', label: 'تمدید', type: 'date', sortable: true },
    { key: 'churnRisk', label: 'ریسک ریزش', type: 'progress' },
    { key: 'status', label: 'وضعیت', type: 'badge' },
  ],
  reviews: [
    { key: 'product', label: 'محصول', type: 'primary', sub: 'author', avatar: 'avatar', sortable: true },
    { key: 'rating', label: 'امتیاز', type: 'rating', sortable: true },
    { key: 'title', label: 'عنوان' },
    { key: 'at', label: 'تاریخ', type: 'relative', sortable: true },
    { key: 'helpful', label: 'مفید', type: 'number', align: 'end' },
    { key: 'status', label: 'وضعیت', type: 'badge' },
  ],
  coupons: [
    { key: 'code', label: 'کد تخفیف', type: 'primary', sub: 'description', sortable: true },
    { key: 'value', label: 'مقدار' },
    { key: 'minOrder', label: 'حداقل سفارش', type: 'currency', align: 'end' },
    { key: 'used', label: 'استفاده', type: 'number', align: 'end', sortable: true },
    { key: 'to', label: 'انقضا', type: 'date', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge' },
  ],
  inventory: [
    { key: 'product', label: 'محصول', type: 'primary', sub: 'sku', avatar: 'image', sortable: true },
    { key: 'warehouse', label: 'انبار' },
    { key: 'stock', label: 'موجودی', type: 'number', align: 'end', sortable: true },
    { key: 'reserved', label: 'رزرو', type: 'number', align: 'end' },
    { key: 'incoming', label: 'ورودی', type: 'number', align: 'end' },
    { key: 'updatedAt', label: 'به‌روزرسانی', type: 'relative', sortable: true },
  ],
  drivers: [
    { key: 'name', label: 'راننده', type: 'primary', sub: 'vehicle', avatar: 'avatar', sortable: true },
    { key: 'plate', label: 'پلاک' },
    { key: 'zone', label: 'منطقه' },
    { key: 'deliveries', label: 'تحویل‌ها', type: 'number', align: 'end', sortable: true },
    { key: 'onTimeRate', label: 'تحویل به‌موقع', type: 'progress', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge' },
  ],
  warehouses: [
    { key: 'name', label: 'انبار', type: 'primary', sub: 'city', sortable: true },
    { key: 'capacity', label: 'ظرفیت', type: 'number', align: 'end' },
    { key: 'used', label: 'اشغال‌شده', type: 'number', align: 'end', sortable: true },
    { key: 'shipments', label: 'محموله', type: 'number', align: 'end', sortable: true },
    { key: 'staff', label: 'کارکنان', type: 'number', align: 'end' },
    { key: 'status', label: 'وضعیت', type: 'badge' },
  ],
  files: [
    { key: 'name', label: 'نام', type: 'primary', sub: 'owner', sortable: true },
    { key: 'type', label: 'نوع' },
    { key: 'size', label: 'حجم' },
    { key: 'at', label: 'تاریخ', type: 'relative', sortable: true },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  media: [
    { key: 'name', label: 'فایل', type: 'primary', sub: 'dimensions', avatar: 'url', sortable: true },
    { key: 'size', label: 'حجم' },
    { key: 'uploadedBy', label: 'بارگذار' },
    { key: 'at', label: 'تاریخ', type: 'relative', sortable: true },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  roles: [
    { key: 'label', label: 'نقش', type: 'primary', sub: 'id', sortable: true },
    { key: 'users', label: 'کاربران', type: 'number', align: 'end', sortable: true },
    { key: 'level', label: 'سطح دسترسی', type: 'progress', sortable: true },
  ],
  teams: [
    { key: 'name', label: 'تیم', type: 'primary', sub: 'lead', sortable: true },
    { key: 'members', label: 'اعضا', type: 'number', align: 'end', sortable: true },
    { key: 'progress', label: 'ظرفیت', type: 'progress', sortable: true },
  ],
  departments: [
    { key: 'name', label: 'دپارتمان', type: 'primary', sub: 'head', sortable: true },
    { key: 'headcount', label: 'نفرات', type: 'number', align: 'end', sortable: true },
    { key: 'location', label: 'موقعیت' },
    { key: 'budget', label: 'بودجه', type: 'currency', align: 'end', sortable: true },
  ],
  invitations: [
    { key: 'email', label: 'ایمیل', type: 'primary', sub: 'role', sortable: true },
    { key: 'team', label: 'تیم' },
    { key: 'sentAt', label: 'ارسال', type: 'relative', sortable: true },
    { key: 'expiresIn', label: 'انقضا (روز)', type: 'number', align: 'end' },
    { key: 'status', label: 'وضعیت', type: 'badge' },
  ],
  sessions: [
    { key: 'device', label: 'دستگاه', type: 'primary', sub: 'ip', sortable: true },
    { key: 'browser', label: 'مرورگر' },
    { key: 'location', label: 'موقعیت' },
    { key: 'lastSeen', label: 'آخرین فعالیت', type: 'relative', sortable: true },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  notes: [
    { key: 'title', label: 'عنوان', type: 'primary', sub: 'body', sortable: true },
    { key: 'at', label: 'تاریخ', type: 'relative', sortable: true },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  'ai/prompts': [
    { key: 'title', label: 'پرامپت', type: 'primary', sub: 'categoryLabel', sortable: true },
    { key: 'usage', label: 'استفاده', type: 'number', align: 'end', sortable: true },
    { key: 'author', label: 'سازنده' },
    { key: 'updatedAt', label: 'به‌روزرسانی', type: 'relative', sortable: true },
    { key: 'actions', label: 'عملیات', type: 'actions' },
  ],
  'ai/scheduler': [
    { key: 'name', label: 'کار', type: 'primary', sub: 'cron', sortable: true },
    { key: 'model', label: 'مدل' },
    { key: 'runs', label: 'اجراها', type: 'number', align: 'end', sortable: true },
    { key: 'lastRun', label: 'آخرین اجرا', type: 'relative', sortable: true },
    { key: 'status', label: 'وضعیت', type: 'badge' },
  ],
};

export default COLUMNS;
