/**
 * Builds src/locales/content-ar.js — the Arabic phrase book for demo content.
 *   node tools/i18n/build-ar.mjs
 * Sources: tools/i18n/keys.json (Persian keys) + tools/i18n/ar/*.tsv
 * (`index<TAB>Arabic`) + tools/i18n/patterns-ar.txt (regex rules).
 */
import fs from 'node:fs';
const here = (p) => new URL(p, import.meta.url);
const keys = JSON.parse(fs.readFileSync(here('./keys.json'), 'utf8'));
const { default: en } = await import('../../src/locales/content-en.js');
const EDGE = /^[\s—–·•:،,;()«»“”"]+|[\s—–·•:،,;()«»“”"]+$/g;
const book = {};
for (const file of fs.readdirSync(here('./ar/')).filter((f) => f.endsWith('.tsv')).sort()) {
  for (const line of fs.readFileSync(here(`./ar/${file}`), 'utf8').split('\n')) {
    if (!line.trim()) continue;
    const tab = line.indexOf('\t');
    const key = keys[Number(line.slice(0, tab))];
    const value = line.slice(tab + 1).trim();
    if (key === undefined) { console.warn('bad index', file, line.slice(0, 20)); continue; }
    if (value) book[key] = value;
  }
}
/* Edge-punctuated template fragments reuse the bare translation. */
for (const key of Object.keys(en)) {
  if (book[key] !== undefined) continue;
  const bare = key.replace(EDGE, '');
  if (bare !== key && book[bare] !== undefined) {
    const lead = key.slice(0, key.indexOf(bare));
    const tail = key.slice(key.indexOf(bare) + bare.length);
    book[key] = `${lead}${book[bare]}${tail}`.trim();
  }
}
const patterns = fs.existsSync(here('./patterns-ar.txt')) ? fs.readFileSync(here('./patterns-ar.txt'), 'utf8').trimEnd() : '';
const body = Object.entries(book).sort(([a], [b]) => a.localeCompare(b)).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n');
fs.writeFileSync(here('../../src/locales/content-ar.js'), `/**
 * Arabic phrase book for the demo *content* (records, dashboards, charts,
 * dialogs). Generated by tools/i18n/build-ar.mjs — keys are the authored
 * Persian copy. Loaded lazily by \`main.js\` only when Arabic is active.
 */
export default {
${body}
};

/** Rules for composed copy with numbers or names (captured groups are translated too). */
export const patterns = [
${patterns}
];
`);
const missing = keys.filter((k) => book[k] === undefined).length;
console.log('ar entries', Object.keys(book).length, 'missing', missing, 'of', keys.length);
