/**
 * NOVAADMIN — navigation & SEO generator
 * ------------------------------------------------------------------
 * Derives machine-readable navigation from the single source of truth
 * (`tools/manifest.mjs`) plus the generated page titles, then writes:
 *
 *   src/data/navigation.js   → flat page index (search, sitemap page, docs)
 *   public/sitemap.xml       → every page, ready for a static host / crawler
 *   public/robots.txt        → sitemap pointer + sensible defaults
 *
 * Run standalone with `npm run gen:nav`, or as part of `npm run gen:all`.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { sidebar, extraPages } from './manifest.mjs';
import { config } from '../src/config/config.js';
import { pageTitles, pageMeta } from '../src/locales/generated.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SITE = (process.env.NOVA_SITE_URL ?? config.website).replace(/\/+$/, '');

const LANGS = ['fa', 'en', 'ar'];

/* ------------------------------------------------------------------ helpers */

/**
 * Walks the manifest tree and returns every page with its ancestry.
 * The manifest nests twice: `sidebar[] → section.items[] → group.children[]`,
 * so both keys are traversed.
 */
function walk(items, trail = []) {
  const out = [];
  for (const item of items) {
    const nextTrail = item.url ? [...trail, { id: item.id, label: item.label, url: item.url }] : trail;
    if (item.url) {
      out.push({
        id: item.id,
        url: item.url,
        icon: item.icon ?? 'circle',
        badge: item.badge ?? null,
        children: (item.children ?? []).length,
        parents: trail.map((parent) => ({ id: parent.id, label: parent.label, url: parent.url })),
        trail: nextTrail.map((node) => ({ id: node.id, label: node.label, url: node.url })),
      });
    }
    const nested = [...(item.items ?? []), ...(item.children ?? [])];
    if (nested.length) out.push(...walk(nested, nextTrail));
  }
  return out;
}

const sectionOf = (url) => pageMeta[url]?.section ?? url.split('/')[0] ?? 'app';
const kindOf = (url) => pageMeta[url]?.kind ?? 'app';

/* --------------------------------------------------------- navigation data */

const entries = walk(sidebar)
  .concat(extraPages.map((page) => ({ id: page.url, url: page.url, icon: 'window', badge: null, children: 0, parents: [], trail: [] })))
  .filter((entry, index, list) => list.findIndex((other) => other.url === entry.url) === index)
  .sort((a, b) => a.url.localeCompare(b.url));

const navigation = entries.map((entry) => ({
  url: entry.url,
  id: entry.id,
  section: sectionOf(entry.url),
  kind: kindOf(entry.url),
  icon: entry.icon,
  badge: entry.badge ? { text: entry.badge.text, variant: entry.badge.variant ?? 'primary' } : null,
  parents: entry.parents.map((parent) => ({
    id: parent.id,
    url: parent.url,
    label: LANGS.reduce((acc, lang) => ({ ...acc, [lang]: parent.label?.[lang] ?? parent.label?.fa ?? parent.id }), {}),
  })),
  title: LANGS.reduce((acc, lang) => ({ ...acc, [lang]: pageTitles[lang]?.[entry.url] ?? pageTitles.fa?.[entry.url] ?? entry.url }), {}),
}));

/** Section buckets keep the sitemap page and the empty search state useful. */
const sections = [...new Set(navigation.map((entry) => entry.section))];

const file = `/* AUTO-GENERATED by tools/gen-nav.mjs — do not edit by hand. */
/**
 * Flat index of every page in the template, used by:
 *   • the search results page (empty state → browse)
 *   • the command palette ("all pages")
 *   • documentation sidebars
 *
 * Each entry: { url, id, section, kind, icon, badge, parents[], title{fa,en,ar} }
 */
export const navigation = ${JSON.stringify(navigation, null, 2)};

/** Section ids in sidebar order — handy for grouping. */
export const navigationSections = ${JSON.stringify(sections, null, 2)};

/** Total number of shipped pages (excluding the docs pages of the docs folder itself). */
export const navigationCount = ${navigation.length};

export default navigation;
`;

fs.writeFileSync(path.join(ROOT, 'src/data/navigation.js'), file, 'utf8');

/* ----------------------------------------------------------- robots + sitemap */

const robots = `User-agent: *
Allow: /

# Development-only tooling lives outside the deployable output.
Disallow: /node_modules/
Disallow: /tools/

Sitemap: ${SITE}/sitemap.xml
`;

const today = config.releaseDate ?? new Date().toISOString().slice(0, 10);
const priority = (url) => (url === 'index.html' ? '1.0' : url.startsWith('dashboards/') ? '0.9' : url.includes('/') ? '0.7' : '0.6');
const urls = ['index.html', ...navigation.map((entry) => entry.url)];

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tools/gen-nav.mjs — ${urls.length} URLs -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    (url) => `  <url>
    <loc>${SITE}/${url}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${url === 'index.html' ? 'weekly' : 'monthly'}</changefreq>
    <priority>${priority(url)}</priority>
  </url>`,
  )
  .join('\n')}
</urlset>
`;

fs.writeFileSync(path.join(ROOT, 'public/robots.txt'), robots, 'utf8');
fs.writeFileSync(path.join(ROOT, 'public/sitemap.xml'), sitemap, 'utf8');

console.log(`✔ navigation.js  → ${navigation.length} pages across ${sections.length} sections`);
console.log(`✔ robots.txt + sitemap.xml → ${urls.length} URLs (${SITE})`);
